export enum FormDataEnum {
    email = "email",
    password = "password",
    password_confirm = "password_confirm",
    role = "role",
    token = "token",
    minEndOrderFromNowInHours = "minEndOrderFromNowInHours",
    minDateToAcceptOfferInHours = "minDateToAcceptOfferInHours",
    minDiffBetweenStartTripAndEndOrderForAllPaymentsInHours = "minDiffBetweenStartTripAndEndOrderForAllPaymentsInHours",
    minDiffBetweenStartTripAndEndOrderInHours = "minDiffBetweenStartTripAndEndOrderInHours",
    payRestOfPriceWarningBeforeStartTripInHours = "payRestOfPriceWarningBeforeStartTripInHours",
    payInvoiceWarningAfterAcceptOfferInHours = "payInvoiceWarningAfterAcceptOfferInHours",
    tripDepositInPercentage = "tripDepositInPercentage",
    tripCancelFeePercentageForDemander = "tripCancelFeePercentageForDemander",
    tripCancelFeeAfterLimitPercentageForDemander = "tripCancelFeeAfterLimitPercentageForDemander",
    tripOfferCommissionPercentage = "tripOfferCommissionPercentage",
    tripCancelPenaltyPercentageForTransporterFromCompany = "tripCancelPenaltyPercentageForTransporterFromCompany",
    tripCancelPenaltyMinAmountInCzkForTransporterFromCompany = "tripCancelPenaltyMinAmountInCzkForTransporterFromCompany",
    tripCancelPenaltyPercentageForTransporterFromDemander = "tripCancelPenaltyPercentageForTransporterFromDemander",
    tripCancelPenaltyMinAmountInCzkForTransporterFromDemander = "tripCancelPenaltyMinAmountInCzkForTransporterFromDemander",
    tripCancelPenaltyLimitInDays = "tripCancelPenaltyLimitInDays",
    tripCancelPenaltyAfterLimitPercentageForTransporter = "tripCancelPenaltyAfterLimitPercentageForTransporter",
}