/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessTokenDto
 */
export interface AccessTokenDto {
    /**
     * 
     * @type {string}
     * @memberof AccessTokenDto
     */
    token: string;
    /**
     * 
     * @type {Date}
     * @memberof AccessTokenDto
     */
    expireDate: Date;
}

/**
 * Check if a given object implements the AccessTokenDto interface.
 */
export function instanceOfAccessTokenDto(value: object): value is AccessTokenDto {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('expireDate' in value) || value['expireDate'] === undefined) return false;
    return true;
}

export function AccessTokenDtoFromJSON(json: any): AccessTokenDto {
    return AccessTokenDtoFromJSONTyped(json, false);
}

export function AccessTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessTokenDto {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'expireDate': (new Date(json['expireDate'])),
    };
}

export function AccessTokenDtoToJSON(json: any): AccessTokenDto {
    return AccessTokenDtoToJSONTyped(json, false);
}

export function AccessTokenDtoToJSONTyped(value?: AccessTokenDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'expireDate': value['expireDate'].toISOString(),
    };
}

