/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleRequestDto } from './VehicleRequestDto';
import {
    VehicleRequestDtoFromJSON,
    VehicleRequestDtoFromJSONTyped,
    VehicleRequestDtoToJSON,
    VehicleRequestDtoToJSONTyped,
} from './VehicleRequestDto';

/**
 * 
 * @export
 * @interface AddVehicleRequestDto
 */
export interface AddVehicleRequestDto {
    /**
     * 
     * @type {VehicleRequestDto}
     * @memberof AddVehicleRequestDto
     */
    info?: VehicleRequestDto;
}

/**
 * Check if a given object implements the AddVehicleRequestDto interface.
 */
export function instanceOfAddVehicleRequestDto(value: object): value is AddVehicleRequestDto {
    return true;
}

export function AddVehicleRequestDtoFromJSON(json: any): AddVehicleRequestDto {
    return AddVehicleRequestDtoFromJSONTyped(json, false);
}

export function AddVehicleRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddVehicleRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'info': json['info'] == null ? undefined : VehicleRequestDtoFromJSON(json['info']),
    };
}

export function AddVehicleRequestDtoToJSON(json: any): AddVehicleRequestDto {
    return AddVehicleRequestDtoToJSONTyped(json, false);
}

export function AddVehicleRequestDtoToJSONTyped(value?: AddVehicleRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'info': VehicleRequestDtoToJSON(value['info']),
    };
}

