/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferInfoResponseDto } from './TransferInfoResponseDto';
import {
    TransferInfoResponseDtoFromJSON,
    TransferInfoResponseDtoFromJSONTyped,
    TransferInfoResponseDtoToJSON,
    TransferInfoResponseDtoToJSONTyped,
} from './TransferInfoResponseDto';
import type { VehicleResponseDto } from './VehicleResponseDto';
import {
    VehicleResponseDtoFromJSON,
    VehicleResponseDtoFromJSONTyped,
    VehicleResponseDtoToJSON,
    VehicleResponseDtoToJSONTyped,
} from './VehicleResponseDto';
import type { UserConfigResponseDto } from './UserConfigResponseDto';
import {
    UserConfigResponseDtoFromJSON,
    UserConfigResponseDtoFromJSONTyped,
    UserConfigResponseDtoToJSON,
    UserConfigResponseDtoToJSONTyped,
} from './UserConfigResponseDto';
import type { UserAddressResponseDto } from './UserAddressResponseDto';
import {
    UserAddressResponseDtoFromJSON,
    UserAddressResponseDtoFromJSONTyped,
    UserAddressResponseDtoToJSON,
    UserAddressResponseDtoToJSONTyped,
} from './UserAddressResponseDto';
import type { TransporterRequirementsResponseDto } from './TransporterRequirementsResponseDto';
import {
    TransporterRequirementsResponseDtoFromJSON,
    TransporterRequirementsResponseDtoFromJSONTyped,
    TransporterRequirementsResponseDtoToJSON,
    TransporterRequirementsResponseDtoToJSONTyped,
} from './TransporterRequirementsResponseDto';

/**
 * 
 * @export
 * @interface AdminUserDetailResponseDto
 */
export interface AdminUserDetailResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AdminUserDetailResponseDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDetailResponseDto
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof AdminUserDetailResponseDto
     */
    active: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminUserDetailResponseDto
     */
    banned: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminUserDetailResponseDto
     */
    isVerifiedForTransporting: boolean;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDetailResponseDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDetailResponseDto
     */
    surname: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDetailResponseDto
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDetailResponseDto
     */
    ico: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDetailResponseDto
     */
    dic: string;
    /**
     * 
     * @type {boolean}
     * @memberof AdminUserDetailResponseDto
     */
    isCompany: boolean;
    /**
     * 
     * @type {UserAddressResponseDto}
     * @memberof AdminUserDetailResponseDto
     */
    address?: UserAddressResponseDto;
    /**
     * 
     * @type {UserAddressResponseDto}
     * @memberof AdminUserDetailResponseDto
     */
    mailingAddress?: UserAddressResponseDto;
    /**
     * 
     * @type {TransferInfoResponseDto}
     * @memberof AdminUserDetailResponseDto
     */
    transferInfo?: TransferInfoResponseDto;
    /**
     * 
     * @type {TransporterRequirementsResponseDto}
     * @memberof AdminUserDetailResponseDto
     */
    transporterRequirements?: TransporterRequirementsResponseDto;
    /**
     * 
     * @type {Array<VehicleResponseDto>}
     * @memberof AdminUserDetailResponseDto
     */
    vehicles: Array<VehicleResponseDto>;
    /**
     * 
     * @type {Array<UserConfigResponseDto>}
     * @memberof AdminUserDetailResponseDto
     */
    userConfigs: Array<UserConfigResponseDto>;
}

/**
 * Check if a given object implements the AdminUserDetailResponseDto interface.
 */
export function instanceOfAdminUserDetailResponseDto(value: object): value is AdminUserDetailResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('banned' in value) || value['banned'] === undefined) return false;
    if (!('isVerifiedForTransporting' in value) || value['isVerifiedForTransporting'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('surname' in value) || value['surname'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('ico' in value) || value['ico'] === undefined) return false;
    if (!('dic' in value) || value['dic'] === undefined) return false;
    if (!('isCompany' in value) || value['isCompany'] === undefined) return false;
    if (!('vehicles' in value) || value['vehicles'] === undefined) return false;
    if (!('userConfigs' in value) || value['userConfigs'] === undefined) return false;
    return true;
}

export function AdminUserDetailResponseDtoFromJSON(json: any): AdminUserDetailResponseDto {
    return AdminUserDetailResponseDtoFromJSONTyped(json, false);
}

export function AdminUserDetailResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserDetailResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'active': json['active'],
        'banned': json['banned'],
        'isVerifiedForTransporting': json['isVerifiedForTransporting'],
        'name': json['name'],
        'surname': json['surname'],
        'phoneNumber': json['phoneNumber'],
        'ico': json['ico'],
        'dic': json['dic'],
        'isCompany': json['isCompany'],
        'address': json['address'] == null ? undefined : UserAddressResponseDtoFromJSON(json['address']),
        'mailingAddress': json['mailingAddress'] == null ? undefined : UserAddressResponseDtoFromJSON(json['mailingAddress']),
        'transferInfo': json['transferInfo'] == null ? undefined : TransferInfoResponseDtoFromJSON(json['transferInfo']),
        'transporterRequirements': json['transporterRequirements'] == null ? undefined : TransporterRequirementsResponseDtoFromJSON(json['transporterRequirements']),
        'vehicles': ((json['vehicles'] as Array<any>).map(VehicleResponseDtoFromJSON)),
        'userConfigs': ((json['userConfigs'] as Array<any>).map(UserConfigResponseDtoFromJSON)),
    };
}

export function AdminUserDetailResponseDtoToJSON(json: any): AdminUserDetailResponseDto {
    return AdminUserDetailResponseDtoToJSONTyped(json, false);
}

export function AdminUserDetailResponseDtoToJSONTyped(value?: AdminUserDetailResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'active': value['active'],
        'banned': value['banned'],
        'isVerifiedForTransporting': value['isVerifiedForTransporting'],
        'name': value['name'],
        'surname': value['surname'],
        'phoneNumber': value['phoneNumber'],
        'ico': value['ico'],
        'dic': value['dic'],
        'isCompany': value['isCompany'],
        'address': UserAddressResponseDtoToJSON(value['address']),
        'mailingAddress': UserAddressResponseDtoToJSON(value['mailingAddress']),
        'transferInfo': TransferInfoResponseDtoToJSON(value['transferInfo']),
        'transporterRequirements': TransporterRequirementsResponseDtoToJSON(value['transporterRequirements']),
        'vehicles': ((value['vehicles'] as Array<any>).map(VehicleResponseDtoToJSON)),
        'userConfigs': ((value['userConfigs'] as Array<any>).map(UserConfigResponseDtoToJSON)),
    };
}

