/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AdminCloseTripOfferReason = {
    DEMANDER_GENERAL: 'DEMANDER_GENERAL',
    DEMANDER_UNPAID: 'DEMANDER_UNPAID',
    TRANSPORTER_GENERAL: 'TRANSPORTER_GENERAL',
    GENERAL: 'GENERAL'
} as const;
export type AdminCloseTripOfferReason = typeof AdminCloseTripOfferReason[keyof typeof AdminCloseTripOfferReason];


export function instanceOfAdminCloseTripOfferReason(value: any): boolean {
    for (const key in AdminCloseTripOfferReason) {
        if (Object.prototype.hasOwnProperty.call(AdminCloseTripOfferReason, key)) {
            if (AdminCloseTripOfferReason[key as keyof typeof AdminCloseTripOfferReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AdminCloseTripOfferReasonFromJSON(json: any): AdminCloseTripOfferReason {
    return AdminCloseTripOfferReasonFromJSONTyped(json, false);
}

export function AdminCloseTripOfferReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminCloseTripOfferReason {
    return json as AdminCloseTripOfferReason;
}

export function AdminCloseTripOfferReasonToJSON(value?: AdminCloseTripOfferReason | null): any {
    return value as any;
}

export function AdminCloseTripOfferReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): AdminCloseTripOfferReason {
    return value as AdminCloseTripOfferReason;
}

