/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceDto } from './PriceDto';
import {
    PriceDtoFromJSON,
    PriceDtoFromJSONTyped,
    PriceDtoToJSON,
    PriceDtoToJSONTyped,
} from './PriceDto';

/**
 * 
 * @export
 * @interface ChangeOfferRequestDto
 */
export interface ChangeOfferRequestDto {
    /**
     * 
     * @type {Date}
     * @memberof ChangeOfferRequestDto
     */
    endOfferDate: Date;
    /**
     * 
     * @type {number}
     * @memberof ChangeOfferRequestDto
     */
    vehicleId: number;
    /**
     * 
     * @type {PriceDto}
     * @memberof ChangeOfferRequestDto
     */
    price: PriceDto;
}

/**
 * Check if a given object implements the ChangeOfferRequestDto interface.
 */
export function instanceOfChangeOfferRequestDto(value: object): value is ChangeOfferRequestDto {
    if (!('endOfferDate' in value) || value['endOfferDate'] === undefined) return false;
    if (!('vehicleId' in value) || value['vehicleId'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function ChangeOfferRequestDtoFromJSON(json: any): ChangeOfferRequestDto {
    return ChangeOfferRequestDtoFromJSONTyped(json, false);
}

export function ChangeOfferRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeOfferRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'endOfferDate': (new Date(json['endOfferDate'])),
        'vehicleId': json['vehicleId'],
        'price': PriceDtoFromJSON(json['price']),
    };
}

export function ChangeOfferRequestDtoToJSON(json: any): ChangeOfferRequestDto {
    return ChangeOfferRequestDtoToJSONTyped(json, false);
}

export function ChangeOfferRequestDtoToJSONTyped(value?: ChangeOfferRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endOfferDate': value['endOfferDate'].toISOString(),
        'vehicleId': value['vehicleId'],
        'price': PriceDtoToJSON(value['price']),
    };
}

