/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CloseTripOfferReason } from './CloseTripOfferReason';
import {
    CloseTripOfferReasonFromJSON,
    CloseTripOfferReasonFromJSONTyped,
    CloseTripOfferReasonToJSON,
    CloseTripOfferReasonToJSONTyped,
} from './CloseTripOfferReason';

/**
 * 
 * @export
 * @interface CloseTripRequestDto
 */
export interface CloseTripRequestDto {
    /**
     * 
     * @type {number}
     * @memberof CloseTripRequestDto
     */
    tripId: number;
    /**
     * 
     * @type {CloseTripOfferReason}
     * @memberof CloseTripRequestDto
     */
    reason?: CloseTripOfferReason;
    /**
     * 
     * @type {string}
     * @memberof CloseTripRequestDto
     */
    reasonText?: string | null;
}



/**
 * Check if a given object implements the CloseTripRequestDto interface.
 */
export function instanceOfCloseTripRequestDto(value: object): value is CloseTripRequestDto {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    return true;
}

export function CloseTripRequestDtoFromJSON(json: any): CloseTripRequestDto {
    return CloseTripRequestDtoFromJSONTyped(json, false);
}

export function CloseTripRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloseTripRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
        'reason': json['reason'] == null ? undefined : CloseTripOfferReasonFromJSON(json['reason']),
        'reasonText': json['reasonText'] == null ? undefined : json['reasonText'],
    };
}

export function CloseTripRequestDtoToJSON(json: any): CloseTripRequestDto {
    return CloseTripRequestDtoToJSONTyped(json, false);
}

export function CloseTripRequestDtoToJSONTyped(value?: CloseTripRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
        'reason': CloseTripOfferReasonToJSON(value['reason']),
        'reasonText': value['reasonText'],
    };
}

