/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloseTripOrderRequestDto
 */
export interface CloseTripOrderRequestDto {
    /**
     * 
     * @type {number}
     * @memberof CloseTripOrderRequestDto
     */
    tripId: number;
}

/**
 * Check if a given object implements the CloseTripOrderRequestDto interface.
 */
export function instanceOfCloseTripOrderRequestDto(value: object): value is CloseTripOrderRequestDto {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    return true;
}

export function CloseTripOrderRequestDtoFromJSON(json: any): CloseTripOrderRequestDto {
    return CloseTripOrderRequestDtoFromJSONTyped(json, false);
}

export function CloseTripOrderRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloseTripOrderRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
    };
}

export function CloseTripOrderRequestDtoToJSON(json: any): CloseTripOrderRequestDto {
    return CloseTripOrderRequestDtoToJSONTyped(json, false);
}

export function CloseTripOrderRequestDtoToJSONTyped(value?: CloseTripOrderRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
    };
}

