/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompletedPublicUploadPhotoItemRequestDto
 */
export interface CompletedPublicUploadPhotoItemRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CompletedPublicUploadPhotoItemRequestDto
     */
    blobName: string;
    /**
     * 
     * @type {string}
     * @memberof CompletedPublicUploadPhotoItemRequestDto
     */
    contentType: string;
    /**
     * 
     * @type {number}
     * @memberof CompletedPublicUploadPhotoItemRequestDto
     */
    fileSize: number;
    /**
     * 
     * @type {string}
     * @memberof CompletedPublicUploadPhotoItemRequestDto
     */
    originalFileName: string;
    /**
     * 
     * @type {number}
     * @memberof CompletedPublicUploadPhotoItemRequestDto
     */
    id: number;
}

/**
 * Check if a given object implements the CompletedPublicUploadPhotoItemRequestDto interface.
 */
export function instanceOfCompletedPublicUploadPhotoItemRequestDto(value: object): value is CompletedPublicUploadPhotoItemRequestDto {
    if (!('blobName' in value) || value['blobName'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('fileSize' in value) || value['fileSize'] === undefined) return false;
    if (!('originalFileName' in value) || value['originalFileName'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CompletedPublicUploadPhotoItemRequestDtoFromJSON(json: any): CompletedPublicUploadPhotoItemRequestDto {
    return CompletedPublicUploadPhotoItemRequestDtoFromJSONTyped(json, false);
}

export function CompletedPublicUploadPhotoItemRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletedPublicUploadPhotoItemRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'blobName': json['blobName'],
        'contentType': json['contentType'],
        'fileSize': json['fileSize'],
        'originalFileName': json['originalFileName'],
        'id': json['id'],
    };
}

export function CompletedPublicUploadPhotoItemRequestDtoToJSON(json: any): CompletedPublicUploadPhotoItemRequestDto {
    return CompletedPublicUploadPhotoItemRequestDtoToJSONTyped(json, false);
}

export function CompletedPublicUploadPhotoItemRequestDtoToJSONTyped(value?: CompletedPublicUploadPhotoItemRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blobName': value['blobName'],
        'contentType': value['contentType'],
        'fileSize': value['fileSize'],
        'originalFileName': value['originalFileName'],
        'id': value['id'],
    };
}

