/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChangeOfferRequestDto } from './ChangeOfferRequestDto';
import {
    ChangeOfferRequestDtoFromJSON,
    ChangeOfferRequestDtoFromJSONTyped,
    ChangeOfferRequestDtoToJSON,
    ChangeOfferRequestDtoToJSONTyped,
} from './ChangeOfferRequestDto';

/**
 * 
 * @export
 * @interface CreateOfferRequestDto
 */
export interface CreateOfferRequestDto {
    /**
     * 
     * @type {number}
     * @memberof CreateOfferRequestDto
     */
    tripId: number;
    /**
     * 
     * @type {ChangeOfferRequestDto}
     * @memberof CreateOfferRequestDto
     */
    changeOffer: ChangeOfferRequestDto;
}

/**
 * Check if a given object implements the CreateOfferRequestDto interface.
 */
export function instanceOfCreateOfferRequestDto(value: object): value is CreateOfferRequestDto {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    if (!('changeOffer' in value) || value['changeOffer'] === undefined) return false;
    return true;
}

export function CreateOfferRequestDtoFromJSON(json: any): CreateOfferRequestDto {
    return CreateOfferRequestDtoFromJSONTyped(json, false);
}

export function CreateOfferRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOfferRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
        'changeOffer': ChangeOfferRequestDtoFromJSON(json['changeOffer']),
    };
}

export function CreateOfferRequestDtoToJSON(json: any): CreateOfferRequestDto {
    return CreateOfferRequestDtoToJSONTyped(json, false);
}

export function CreateOfferRequestDtoToJSONTyped(value?: CreateOfferRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
        'changeOffer': ChangeOfferRequestDtoToJSON(value['changeOffer']),
    };
}

