/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceDto } from './PriceDto';
import {
    PriceDtoFromJSON,
    PriceDtoFromJSONTyped,
    PriceDtoToJSON,
    PriceDtoToJSONTyped,
} from './PriceDto';

/**
 * 
 * @export
 * @interface CreateOfferRequestDto
 */
export interface CreateOfferRequestDto {
    /**
     * 
     * @type {Date}
     * @memberof CreateOfferRequestDto
     */
    endOfferDate: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateOfferRequestDto
     */
    tripId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateOfferRequestDto
     */
    vehicleId: number;
    /**
     * 
     * @type {PriceDto}
     * @memberof CreateOfferRequestDto
     */
    price: PriceDto;
}

/**
 * Check if a given object implements the CreateOfferRequestDto interface.
 */
export function instanceOfCreateOfferRequestDto(value: object): value is CreateOfferRequestDto {
    if (!('endOfferDate' in value) || value['endOfferDate'] === undefined) return false;
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    if (!('vehicleId' in value) || value['vehicleId'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function CreateOfferRequestDtoFromJSON(json: any): CreateOfferRequestDto {
    return CreateOfferRequestDtoFromJSONTyped(json, false);
}

export function CreateOfferRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOfferRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'endOfferDate': (new Date(json['endOfferDate'])),
        'tripId': json['tripId'],
        'vehicleId': json['vehicleId'],
        'price': PriceDtoFromJSON(json['price']),
    };
}

export function CreateOfferRequestDtoToJSON(json: any): CreateOfferRequestDto {
    return CreateOfferRequestDtoToJSONTyped(json, false);
}

export function CreateOfferRequestDtoToJSONTyped(value?: CreateOfferRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endOfferDate': value['endOfferDate'].toISOString(),
        'tripId': value['tripId'],
        'vehicleId': value['vehicleId'],
        'price': PriceDtoToJSON(value['price']),
    };
}

