/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleUploadPhotoItemRequestDto } from './VehicleUploadPhotoItemRequestDto';
import {
    VehicleUploadPhotoItemRequestDtoFromJSON,
    VehicleUploadPhotoItemRequestDtoFromJSONTyped,
    VehicleUploadPhotoItemRequestDtoToJSON,
    VehicleUploadPhotoItemRequestDtoToJSONTyped,
} from './VehicleUploadPhotoItemRequestDto';
import type { VehicleUploadDocumentItemRequestDto } from './VehicleUploadDocumentItemRequestDto';
import {
    VehicleUploadDocumentItemRequestDtoFromJSON,
    VehicleUploadDocumentItemRequestDtoFromJSONTyped,
    VehicleUploadDocumentItemRequestDtoToJSON,
    VehicleUploadDocumentItemRequestDtoToJSONTyped,
} from './VehicleUploadDocumentItemRequestDto';

/**
 * 
 * @export
 * @interface CreateUploadUrlForVehicleFilesRequestDto
 */
export interface CreateUploadUrlForVehicleFilesRequestDto {
    /**
     * 
     * @type {number}
     * @memberof CreateUploadUrlForVehicleFilesRequestDto
     */
    vehicleId: number;
    /**
     * 
     * @type {Array<VehicleUploadPhotoItemRequestDto>}
     * @memberof CreateUploadUrlForVehicleFilesRequestDto
     */
    photos: Array<VehicleUploadPhotoItemRequestDto>;
    /**
     * 
     * @type {Array<VehicleUploadDocumentItemRequestDto>}
     * @memberof CreateUploadUrlForVehicleFilesRequestDto
     */
    documents: Array<VehicleUploadDocumentItemRequestDto>;
}

/**
 * Check if a given object implements the CreateUploadUrlForVehicleFilesRequestDto interface.
 */
export function instanceOfCreateUploadUrlForVehicleFilesRequestDto(value: object): value is CreateUploadUrlForVehicleFilesRequestDto {
    if (!('vehicleId' in value) || value['vehicleId'] === undefined) return false;
    if (!('photos' in value) || value['photos'] === undefined) return false;
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function CreateUploadUrlForVehicleFilesRequestDtoFromJSON(json: any): CreateUploadUrlForVehicleFilesRequestDto {
    return CreateUploadUrlForVehicleFilesRequestDtoFromJSONTyped(json, false);
}

export function CreateUploadUrlForVehicleFilesRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUploadUrlForVehicleFilesRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'vehicleId': json['vehicleId'],
        'photos': ((json['photos'] as Array<any>).map(VehicleUploadPhotoItemRequestDtoFromJSON)),
        'documents': ((json['documents'] as Array<any>).map(VehicleUploadDocumentItemRequestDtoFromJSON)),
    };
}

export function CreateUploadUrlForVehicleFilesRequestDtoToJSON(json: any): CreateUploadUrlForVehicleFilesRequestDto {
    return CreateUploadUrlForVehicleFilesRequestDtoToJSONTyped(json, false);
}

export function CreateUploadUrlForVehicleFilesRequestDtoToJSONTyped(value?: CreateUploadUrlForVehicleFilesRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vehicleId': value['vehicleId'],
        'photos': ((value['photos'] as Array<any>).map(VehicleUploadPhotoItemRequestDtoToJSON)),
        'documents': ((value['documents'] as Array<any>).map(VehicleUploadDocumentItemRequestDtoToJSON)),
    };
}

