/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteTripOfferRequestDto
 */
export interface DeleteTripOfferRequestDto {
    /**
     * 
     * @type {number}
     * @memberof DeleteTripOfferRequestDto
     */
    tripId: number;
    /**
     * 
     * @type {number}
     * @memberof DeleteTripOfferRequestDto
     */
    vehicleId?: number | null;
}

/**
 * Check if a given object implements the DeleteTripOfferRequestDto interface.
 */
export function instanceOfDeleteTripOfferRequestDto(value: object): value is DeleteTripOfferRequestDto {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    return true;
}

export function DeleteTripOfferRequestDtoFromJSON(json: any): DeleteTripOfferRequestDto {
    return DeleteTripOfferRequestDtoFromJSONTyped(json, false);
}

export function DeleteTripOfferRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTripOfferRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
        'vehicleId': json['vehicleId'] == null ? undefined : json['vehicleId'],
    };
}

export function DeleteTripOfferRequestDtoToJSON(json: any): DeleteTripOfferRequestDto {
    return DeleteTripOfferRequestDtoToJSONTyped(json, false);
}

export function DeleteTripOfferRequestDtoToJSONTyped(value?: DeleteTripOfferRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
        'vehicleId': value['vehicleId'],
    };
}

