/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DirectionResponseDto
 */
export interface DirectionResponseDto {
    /**
     * 
     * @type {number}
     * @memberof DirectionResponseDto
     */
    time: number;
    /**
     * 
     * @type {number}
     * @memberof DirectionResponseDto
     */
    distance: number;
    /**
     * 
     * @type {string}
     * @memberof DirectionResponseDto
     */
    polyline: string;
}

/**
 * Check if a given object implements the DirectionResponseDto interface.
 */
export function instanceOfDirectionResponseDto(value: object): value is DirectionResponseDto {
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('distance' in value) || value['distance'] === undefined) return false;
    if (!('polyline' in value) || value['polyline'] === undefined) return false;
    return true;
}

export function DirectionResponseDtoFromJSON(json: any): DirectionResponseDto {
    return DirectionResponseDtoFromJSONTyped(json, false);
}

export function DirectionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'],
        'distance': json['distance'],
        'polyline': json['polyline'],
    };
}

export function DirectionResponseDtoToJSON(json: any): DirectionResponseDto {
    return DirectionResponseDtoToJSONTyped(json, false);
}

export function DirectionResponseDtoToJSONTyped(value?: DirectionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
        'distance': value['distance'],
        'polyline': value['polyline'],
    };
}

