/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DirectionRequestDto
 */
export interface DirectionRequestDto {
    /**
     * 
     * @type {number}
     * @memberof DirectionRequestDto
     */
    time: number;
    /**
     * 
     * @type {number}
     * @memberof DirectionRequestDto
     */
    distance: number;
    /**
     * 
     * @type {string}
     * @memberof DirectionRequestDto
     */
    polyline: string;
}

/**
 * Check if a given object implements the DirectionRequestDto interface.
 */
export function instanceOfDirectionRequestDto(value: object): value is DirectionRequestDto {
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('distance' in value) || value['distance'] === undefined) return false;
    if (!('polyline' in value) || value['polyline'] === undefined) return false;
    return true;
}

export function DirectionRequestDtoFromJSON(json: any): DirectionRequestDto {
    return DirectionRequestDtoFromJSONTyped(json, false);
}

export function DirectionRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectionRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'],
        'distance': json['distance'],
        'polyline': json['polyline'],
    };
}

export function DirectionRequestDtoToJSON(json: any): DirectionRequestDto {
    return DirectionRequestDtoToJSONTyped(json, false);
}

export function DirectionRequestDtoToJSONTyped(value?: DirectionRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
        'distance': value['distance'],
        'polyline': value['polyline'],
    };
}

