/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownloadTripInvoiceRequestDto
 */
export interface DownloadTripInvoiceRequestDto {
    /**
     * 
     * @type {number}
     * @memberof DownloadTripInvoiceRequestDto
     */
    invoiceId: number;
}

/**
 * Check if a given object implements the DownloadTripInvoiceRequestDto interface.
 */
export function instanceOfDownloadTripInvoiceRequestDto(value: object): boolean {
    if (!('invoiceId' in value)) return false;
    return true;
}

export function DownloadTripInvoiceRequestDtoFromJSON(json: any): DownloadTripInvoiceRequestDto {
    return DownloadTripInvoiceRequestDtoFromJSONTyped(json, false);
}

export function DownloadTripInvoiceRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadTripInvoiceRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'invoiceId': json['invoiceId'],
    };
}

export function DownloadTripInvoiceRequestDtoToJSON(value?: DownloadTripInvoiceRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'invoiceId': value['invoiceId'],
    };
}

