/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Language } from './Language';
import {
    LanguageFromJSON,
    LanguageFromJSONTyped,
    LanguageToJSON,
    LanguageToJSONTyped,
} from './Language';

/**
 * 
 * @export
 * @interface EmailConfigLocalizationResponseDto
 */
export interface EmailConfigLocalizationResponseDto {
    /**
     * 
     * @type {Language}
     * @memberof EmailConfigLocalizationResponseDto
     */
    language: Language;
    /**
     * 
     * @type {number}
     * @memberof EmailConfigLocalizationResponseDto
     */
    templateId: number;
}



/**
 * Check if a given object implements the EmailConfigLocalizationResponseDto interface.
 */
export function instanceOfEmailConfigLocalizationResponseDto(value: object): value is EmailConfigLocalizationResponseDto {
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    return true;
}

export function EmailConfigLocalizationResponseDtoFromJSON(json: any): EmailConfigLocalizationResponseDto {
    return EmailConfigLocalizationResponseDtoFromJSONTyped(json, false);
}

export function EmailConfigLocalizationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailConfigLocalizationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'language': LanguageFromJSON(json['language']),
        'templateId': json['templateId'],
    };
}

export function EmailConfigLocalizationResponseDtoToJSON(json: any): EmailConfigLocalizationResponseDto {
    return EmailConfigLocalizationResponseDtoToJSONTyped(json, false);
}

export function EmailConfigLocalizationResponseDtoToJSONTyped(value?: EmailConfigLocalizationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'language': LanguageToJSON(value['language']),
        'templateId': value['templateId'],
    };
}

