/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailConfigResponseDtoUserParams
 */
export interface EmailConfigResponseDtoUserParams {
    /**
     * 
     * @type {string}
     * @memberof EmailConfigResponseDtoUserParams
     */
    role?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailConfigResponseDtoUserParams
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailConfigResponseDtoUserParams
     */
    surname?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailConfigResponseDtoUserParams
     */
    phoneNumber?: string;
}

/**
 * Check if a given object implements the EmailConfigResponseDtoUserParams interface.
 */
export function instanceOfEmailConfigResponseDtoUserParams(value: object): value is EmailConfigResponseDtoUserParams {
    return true;
}

export function EmailConfigResponseDtoUserParamsFromJSON(json: any): EmailConfigResponseDtoUserParams {
    return EmailConfigResponseDtoUserParamsFromJSONTyped(json, false);
}

export function EmailConfigResponseDtoUserParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailConfigResponseDtoUserParams {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['Role'] == null ? undefined : json['Role'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'surname': json['Surname'] == null ? undefined : json['Surname'],
        'phoneNumber': json['PhoneNumber'] == null ? undefined : json['PhoneNumber'],
    };
}

export function EmailConfigResponseDtoUserParamsToJSON(json: any): EmailConfigResponseDtoUserParams {
    return EmailConfigResponseDtoUserParamsToJSONTyped(json, false);
}

export function EmailConfigResponseDtoUserParamsToJSONTyped(value?: EmailConfigResponseDtoUserParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Role': value['role'],
        'Name': value['name'],
        'Surname': value['surname'],
        'PhoneNumber': value['phoneNumber'],
    };
}

