/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
    ErrorCodeToJSONTyped,
} from './ErrorCode';

/**
 * 
 * @export
 * @interface ErrorResponseDto
 */
export interface ErrorResponseDto {
    /**
     * 
     * @type {ErrorCode}
     * @memberof ErrorResponseDto
     */
    errorCode: ErrorCode;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseDto
     */
    message: string;
}



/**
 * Check if a given object implements the ErrorResponseDto interface.
 */
export function instanceOfErrorResponseDto(value: object): value is ErrorResponseDto {
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ErrorResponseDtoFromJSON(json: any): ErrorResponseDto {
    return ErrorResponseDtoFromJSONTyped(json, false);
}

export function ErrorResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': ErrorCodeFromJSON(json['errorCode']),
        'message': json['message'],
    };
}

export function ErrorResponseDtoToJSON(json: any): ErrorResponseDto {
    return ErrorResponseDtoToJSONTyped(json, false);
}

export function ErrorResponseDtoToJSONTyped(value?: ErrorResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorCode': ErrorCodeToJSON(value['errorCode']),
        'message': value['message'],
    };
}

