/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FileCategory = {
    IMAGE: 'IMAGE',
    DOCUMENT: 'DOCUMENT',
    OTHER: 'OTHER',
    UNKNOWN: 'UNKNOWN'
} as const;
export type FileCategory = typeof FileCategory[keyof typeof FileCategory];


export function instanceOfFileCategory(value: any): boolean {
    for (const key in FileCategory) {
        if (Object.prototype.hasOwnProperty.call(FileCategory, key)) {
            if (FileCategory[key as keyof typeof FileCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FileCategoryFromJSON(json: any): FileCategory {
    return FileCategoryFromJSONTyped(json, false);
}

export function FileCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileCategory {
    return json as FileCategory;
}

export function FileCategoryToJSON(value?: FileCategory | null): any {
    return value as any;
}

export function FileCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): FileCategory {
    return value as FileCategory;
}

