/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FinancialDocumentType = {
    PENALTY: 'PENALTY',
    DEPOSIT: 'DEPOSIT',
    INVOICE: 'INVOICE',
    TRIP_INVOICE: 'TRIP_INVOICE'
} as const;
export type FinancialDocumentType = typeof FinancialDocumentType[keyof typeof FinancialDocumentType];


export function instanceOfFinancialDocumentType(value: any): boolean {
    for (const key in FinancialDocumentType) {
        if (Object.prototype.hasOwnProperty.call(FinancialDocumentType, key)) {
            if (FinancialDocumentType[key as keyof typeof FinancialDocumentType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FinancialDocumentTypeFromJSON(json: any): FinancialDocumentType {
    return FinancialDocumentTypeFromJSONTyped(json, false);
}

export function FinancialDocumentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialDocumentType {
    return json as FinancialDocumentType;
}

export function FinancialDocumentTypeToJSON(value?: FinancialDocumentType | null): any {
    return value as any;
}

export function FinancialDocumentTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): FinancialDocumentType {
    return value as FinancialDocumentType;
}

