/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FinishTripRequestDto
 */
export interface FinishTripRequestDto {
    /**
     * 
     * @type {number}
     * @memberof FinishTripRequestDto
     */
    tripId: number;
}

/**
 * Check if a given object implements the FinishTripRequestDto interface.
 */
export function instanceOfFinishTripRequestDto(value: object): value is FinishTripRequestDto {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    return true;
}

export function FinishTripRequestDtoFromJSON(json: any): FinishTripRequestDto {
    return FinishTripRequestDtoFromJSONTyped(json, false);
}

export function FinishTripRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinishTripRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
    };
}

export function FinishTripRequestDtoToJSON(json: any): FinishTripRequestDto {
    return FinishTripRequestDtoToJSONTyped(json, false);
}

export function FinishTripRequestDtoToJSONTyped(value?: FinishTripRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
    };
}

