/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForceCloseTripOrderRequestDto
 */
export interface ForceCloseTripOrderRequestDto {
    /**
     * 
     * @type {number}
     * @memberof ForceCloseTripOrderRequestDto
     */
    tripId: number;
}

/**
 * Check if a given object implements the ForceCloseTripOrderRequestDto interface.
 */
export function instanceOfForceCloseTripOrderRequestDto(value: object): value is ForceCloseTripOrderRequestDto {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    return true;
}

export function ForceCloseTripOrderRequestDtoFromJSON(json: any): ForceCloseTripOrderRequestDto {
    return ForceCloseTripOrderRequestDtoFromJSONTyped(json, false);
}

export function ForceCloseTripOrderRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForceCloseTripOrderRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
    };
}

export function ForceCloseTripOrderRequestDtoToJSON(json: any): ForceCloseTripOrderRequestDto {
    return ForceCloseTripOrderRequestDtoToJSONTyped(json, false);
}

export function ForceCloseTripOrderRequestDtoToJSONTyped(value?: ForceCloseTripOrderRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
    };
}

