/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoPointDto
 */
export interface GeoPointDto {
    /**
     * 
     * @type {number}
     * @memberof GeoPointDto
     */
    lng: number;
    /**
     * 
     * @type {number}
     * @memberof GeoPointDto
     */
    lat: number;
}

/**
 * Check if a given object implements the GeoPointDto interface.
 */
export function instanceOfGeoPointDto(value: object): value is GeoPointDto {
    if (!('lng' in value) || value['lng'] === undefined) return false;
    if (!('lat' in value) || value['lat'] === undefined) return false;
    return true;
}

export function GeoPointDtoFromJSON(json: any): GeoPointDto {
    return GeoPointDtoFromJSONTyped(json, false);
}

export function GeoPointDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoPointDto {
    if (json == null) {
        return json;
    }
    return {
        
        'lng': json['lng'],
        'lat': json['lat'],
    };
}

export function GeoPointDtoToJSON(json: any): GeoPointDto {
    return GeoPointDtoToJSONTyped(json, false);
}

export function GeoPointDtoToJSONTyped(value?: GeoPointDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lng': value['lng'],
        'lat': value['lat'],
    };
}

