/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleUploadPhotoItemRequestDto } from './VehicleUploadPhotoItemRequestDto';
import {
    VehicleUploadPhotoItemRequestDtoFromJSON,
    VehicleUploadPhotoItemRequestDtoFromJSONTyped,
    VehicleUploadPhotoItemRequestDtoToJSON,
    VehicleUploadPhotoItemRequestDtoToJSONTyped,
} from './VehicleUploadPhotoItemRequestDto';
import type { VehicleUploadDocumentItemRequestDto } from './VehicleUploadDocumentItemRequestDto';
import {
    VehicleUploadDocumentItemRequestDtoFromJSON,
    VehicleUploadDocumentItemRequestDtoFromJSONTyped,
    VehicleUploadDocumentItemRequestDtoToJSON,
    VehicleUploadDocumentItemRequestDtoToJSONTyped,
} from './VehicleUploadDocumentItemRequestDto';

/**
 * 
 * @export
 * @interface GetUploadUrlForVehicleFilesRequestDto
 */
export interface GetUploadUrlForVehicleFilesRequestDto {
    /**
     * 
     * @type {number}
     * @memberof GetUploadUrlForVehicleFilesRequestDto
     */
    vehicleId: number;
    /**
     * 
     * @type {Array<VehicleUploadPhotoItemRequestDto>}
     * @memberof GetUploadUrlForVehicleFilesRequestDto
     */
    photos: Array<VehicleUploadPhotoItemRequestDto>;
    /**
     * 
     * @type {Array<VehicleUploadDocumentItemRequestDto>}
     * @memberof GetUploadUrlForVehicleFilesRequestDto
     */
    documents: Array<VehicleUploadDocumentItemRequestDto>;
}

/**
 * Check if a given object implements the GetUploadUrlForVehicleFilesRequestDto interface.
 */
export function instanceOfGetUploadUrlForVehicleFilesRequestDto(value: object): value is GetUploadUrlForVehicleFilesRequestDto {
    if (!('vehicleId' in value) || value['vehicleId'] === undefined) return false;
    if (!('photos' in value) || value['photos'] === undefined) return false;
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function GetUploadUrlForVehicleFilesRequestDtoFromJSON(json: any): GetUploadUrlForVehicleFilesRequestDto {
    return GetUploadUrlForVehicleFilesRequestDtoFromJSONTyped(json, false);
}

export function GetUploadUrlForVehicleFilesRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUploadUrlForVehicleFilesRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'vehicleId': json['vehicleId'],
        'photos': ((json['photos'] as Array<any>).map(VehicleUploadPhotoItemRequestDtoFromJSON)),
        'documents': ((json['documents'] as Array<any>).map(VehicleUploadDocumentItemRequestDtoFromJSON)),
    };
}

export function GetUploadUrlForVehicleFilesRequestDtoToJSON(json: any): GetUploadUrlForVehicleFilesRequestDto {
    return GetUploadUrlForVehicleFilesRequestDtoToJSONTyped(json, false);
}

export function GetUploadUrlForVehicleFilesRequestDtoToJSONTyped(value?: GetUploadUrlForVehicleFilesRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vehicleId': value['vehicleId'],
        'photos': ((value['photos'] as Array<any>).map(VehicleUploadPhotoItemRequestDtoToJSON)),
        'documents': ((value['documents'] as Array<any>).map(VehicleUploadDocumentItemRequestDtoToJSON)),
    };
}

