/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Languages = {
    CZECH: 'CZECH',
    ENGLISH: 'ENGLISH'
} as const;
export type Languages = typeof Languages[keyof typeof Languages];


export function instanceOfLanguages(value: any): boolean {
    for (const key in Languages) {
        if (Object.prototype.hasOwnProperty.call(Languages, key)) {
            if (Languages[key as keyof typeof Languages] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LanguagesFromJSON(json: any): Languages {
    return LanguagesFromJSONTyped(json, false);
}

export function LanguagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Languages {
    return json as Languages;
}

export function LanguagesToJSON(value?: Languages | null): any {
    return value as any;
}

export function LanguagesToJSONTyped(value: any, ignoreDiscriminator: boolean): Languages {
    return value as Languages;
}

