/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Locales = {
    CS_CZ: 'CS_CZ',
    EN_US: 'EN_US'
} as const;
export type Locales = typeof Locales[keyof typeof Locales];


export function instanceOfLocales(value: any): boolean {
    for (const key in Locales) {
        if (Object.prototype.hasOwnProperty.call(Locales, key)) {
            if (Locales[key as keyof typeof Locales] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LocalesFromJSON(json: any): Locales {
    return LocalesFromJSONTyped(json, false);
}

export function LocalesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Locales {
    return json as Locales;
}

export function LocalesToJSON(value?: Locales | null): any {
    return value as any;
}

export function LocalesToJSONTyped(value: any, ignoreDiscriminator: boolean): Locales {
    return value as Locales;
}

