/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppBusinessConfigResponseDto } from './AppBusinessConfigResponseDto';
import {
    AppBusinessConfigResponseDtoFromJSON,
    AppBusinessConfigResponseDtoFromJSONTyped,
    AppBusinessConfigResponseDtoToJSON,
    AppBusinessConfigResponseDtoToJSONTyped,
} from './AppBusinessConfigResponseDto';
import type { CurrentUserDto } from './CurrentUserDto';
import {
    CurrentUserDtoFromJSON,
    CurrentUserDtoFromJSONTyped,
    CurrentUserDtoToJSON,
    CurrentUserDtoToJSONTyped,
} from './CurrentUserDto';
import type { AccessTokenDto } from './AccessTokenDto';
import {
    AccessTokenDtoFromJSON,
    AccessTokenDtoFromJSONTyped,
    AccessTokenDtoToJSON,
    AccessTokenDtoToJSONTyped,
} from './AccessTokenDto';

/**
 * 
 * @export
 * @interface LoginResponseDto
 */
export interface LoginResponseDto {
    /**
     * 
     * @type {CurrentUserDto}
     * @memberof LoginResponseDto
     */
    user: CurrentUserDto;
    /**
     * 
     * @type {AccessTokenDto}
     * @memberof LoginResponseDto
     */
    token: AccessTokenDto;
    /**
     * 
     * @type {AppBusinessConfigResponseDto}
     * @memberof LoginResponseDto
     */
    appBusinessConfig: AppBusinessConfigResponseDto;
}

/**
 * Check if a given object implements the LoginResponseDto interface.
 */
export function instanceOfLoginResponseDto(value: object): value is LoginResponseDto {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('appBusinessConfig' in value) || value['appBusinessConfig'] === undefined) return false;
    return true;
}

export function LoginResponseDtoFromJSON(json: any): LoginResponseDto {
    return LoginResponseDtoFromJSONTyped(json, false);
}

export function LoginResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'user': CurrentUserDtoFromJSON(json['user']),
        'token': AccessTokenDtoFromJSON(json['token']),
        'appBusinessConfig': AppBusinessConfigResponseDtoFromJSON(json['appBusinessConfig']),
    };
}

export function LoginResponseDtoToJSON(json: any): LoginResponseDto {
    return LoginResponseDtoToJSONTyped(json, false);
}

export function LoginResponseDtoToJSONTyped(value?: LoginResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': CurrentUserDtoToJSON(value['user']),
        'token': AccessTokenDtoToJSON(value['token']),
        'appBusinessConfig': AppBusinessConfigResponseDtoToJSON(value['appBusinessConfig']),
    };
}

