/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationSettingsNewTripDataResponseDto
 */
export interface NotificationSettingsNewTripDataResponseDto {
    /**
     * 
     * @type {number}
     * @memberof NotificationSettingsNewTripDataResponseDto
     */
    radiusInMeters: number;
}

/**
 * Check if a given object implements the NotificationSettingsNewTripDataResponseDto interface.
 */
export function instanceOfNotificationSettingsNewTripDataResponseDto(value: object): value is NotificationSettingsNewTripDataResponseDto {
    if (!('radiusInMeters' in value) || value['radiusInMeters'] === undefined) return false;
    return true;
}

export function NotificationSettingsNewTripDataResponseDtoFromJSON(json: any): NotificationSettingsNewTripDataResponseDto {
    return NotificationSettingsNewTripDataResponseDtoFromJSONTyped(json, false);
}

export function NotificationSettingsNewTripDataResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationSettingsNewTripDataResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'radiusInMeters': json['radiusInMeters'],
    };
}

export function NotificationSettingsNewTripDataResponseDtoToJSON(json: any): NotificationSettingsNewTripDataResponseDto {
    return NotificationSettingsNewTripDataResponseDtoToJSONTyped(json, false);
}

export function NotificationSettingsNewTripDataResponseDtoToJSONTyped(value?: NotificationSettingsNewTripDataResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'radiusInMeters': value['radiusInMeters'],
    };
}

