/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Notifications = {
    NEW_OFFER_FROM_TRANSPORTER: 'NEW_OFFER_FROM_TRANSPORTER'
} as const;
export type Notifications = typeof Notifications[keyof typeof Notifications];


export function instanceOfNotifications(value: any): boolean {
    for (const key in Notifications) {
        if (Object.prototype.hasOwnProperty.call(Notifications, key)) {
            if (Notifications[key as keyof typeof Notifications] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NotificationsFromJSON(json: any): Notifications {
    return NotificationsFromJSONTyped(json, false);
}

export function NotificationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notifications {
    return json as Notifications;
}

export function NotificationsToJSON(value?: Notifications | null): any {
    return value as any;
}

export function NotificationsToJSONTyped(value: any, ignoreDiscriminator: boolean): Notifications {
    return value as Notifications;
}

