/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceDto } from './PriceDto';
import {
    PriceDtoFromJSON,
    PriceDtoFromJSONTyped,
    PriceDtoToJSON,
    PriceDtoToJSONTyped,
} from './PriceDto';

/**
 * 
 * @export
 * @interface OfferRequestDto
 */
export interface OfferRequestDto {
    /**
     * 
     * @type {Date}
     * @memberof OfferRequestDto
     */
    endOfferDate: Date;
    /**
     * 
     * @type {number}
     * @memberof OfferRequestDto
     */
    vehicleId: number;
    /**
     * 
     * @type {PriceDto}
     * @memberof OfferRequestDto
     */
    price: PriceDto;
}

/**
 * Check if a given object implements the OfferRequestDto interface.
 */
export function instanceOfOfferRequestDto(value: object): value is OfferRequestDto {
    if (!('endOfferDate' in value) || value['endOfferDate'] === undefined) return false;
    if (!('vehicleId' in value) || value['vehicleId'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function OfferRequestDtoFromJSON(json: any): OfferRequestDto {
    return OfferRequestDtoFromJSONTyped(json, false);
}

export function OfferRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfferRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'endOfferDate': (new Date(json['endOfferDate'])),
        'vehicleId': json['vehicleId'],
        'price': PriceDtoFromJSON(json['price']),
    };
}

export function OfferRequestDtoToJSON(json: any): OfferRequestDto {
    return OfferRequestDtoToJSONTyped(json, false);
}

export function OfferRequestDtoToJSONTyped(value?: OfferRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endOfferDate': value['endOfferDate'].toISOString(),
        'vehicleId': value['vehicleId'],
        'price': PriceDtoToJSON(value['price']),
    };
}

