/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OfferCanceledReason = {
    SELF_CANCELED: 'SELF_CANCELED',
    CANCELED_DUE_TO_OFFER_CONFLICT: 'CANCELED_DUE_TO_OFFER_CONFLICT'
} as const;
export type OfferCanceledReason = typeof OfferCanceledReason[keyof typeof OfferCanceledReason];


export function instanceOfOfferCanceledReason(value: any): boolean {
    for (const key in OfferCanceledReason) {
        if (Object.prototype.hasOwnProperty.call(OfferCanceledReason, key)) {
            if (OfferCanceledReason[key as keyof typeof OfferCanceledReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OfferCanceledReasonFromJSON(json: any): OfferCanceledReason {
    return OfferCanceledReasonFromJSONTyped(json, false);
}

export function OfferCanceledReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfferCanceledReason {
    return json as OfferCanceledReason;
}

export function OfferCanceledReasonToJSON(value?: OfferCanceledReason | null): any {
    return value as any;
}

export function OfferCanceledReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): OfferCanceledReason {
    return value as OfferCanceledReason;
}

