/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayedOfferRequestDto
 */
export interface PayedOfferRequestDto {
    /**
     * 
     * @type {number}
     * @memberof PayedOfferRequestDto
     */
    offerId: number;
}

/**
 * Check if a given object implements the PayedOfferRequestDto interface.
 */
export function instanceOfPayedOfferRequestDto(value: object): value is PayedOfferRequestDto {
    if (!('offerId' in value) || value['offerId'] === undefined) return false;
    return true;
}

export function PayedOfferRequestDtoFromJSON(json: any): PayedOfferRequestDto {
    return PayedOfferRequestDtoFromJSONTyped(json, false);
}

export function PayedOfferRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayedOfferRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'offerId': json['offerId'],
    };
}

export function PayedOfferRequestDtoToJSON(json: any): PayedOfferRequestDto {
    return PayedOfferRequestDtoToJSONTyped(json, false);
}

export function PayedOfferRequestDtoToJSONTyped(value?: PayedOfferRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offerId': value['offerId'],
    };
}

