/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Country } from './Country';
import {
    CountryFromJSON,
    CountryFromJSONTyped,
    CountryToJSON,
    CountryToJSONTyped,
} from './Country';

/**
 * 
 * @export
 * @interface PlaceItemResponseDto
 */
export interface PlaceItemResponseDto {
    /**
     * 
     * @type {string}
     * @memberof PlaceItemResponseDto
     */
    city: string;
    /**
     * 
     * @type {Country}
     * @memberof PlaceItemResponseDto
     */
    country: Country;
}



/**
 * Check if a given object implements the PlaceItemResponseDto interface.
 */
export function instanceOfPlaceItemResponseDto(value: object): value is PlaceItemResponseDto {
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    return true;
}

export function PlaceItemResponseDtoFromJSON(json: any): PlaceItemResponseDto {
    return PlaceItemResponseDtoFromJSONTyped(json, false);
}

export function PlaceItemResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceItemResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'],
        'country': CountryFromJSON(json['country']),
    };
}

export function PlaceItemResponseDtoToJSON(json: any): PlaceItemResponseDto {
    return PlaceItemResponseDtoToJSONTyped(json, false);
}

export function PlaceItemResponseDtoToJSONTyped(value?: PlaceItemResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'country': CountryToJSON(value['country']),
    };
}

