/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PlaceResolution = {
    STREET: 'STREET',
    LOCALITY: 'LOCALITY'
} as const;
export type PlaceResolution = typeof PlaceResolution[keyof typeof PlaceResolution];


export function instanceOfPlaceResolution(value: any): boolean {
    return Object.values(PlaceResolution).includes(value);
}

export function PlaceResolutionFromJSON(json: any): PlaceResolution {
    return PlaceResolutionFromJSONTyped(json, false);
}

export function PlaceResolutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceResolution {
    return json as PlaceResolution;
}

export function PlaceResolutionToJSON(value?: PlaceResolution | null): any {
    return value as any;
}

