/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';

/**
 * 
 * @export
 * @interface PriceDto
 */
export interface PriceDto {
    /**
     * 
     * @type {number}
     * @memberof PriceDto
     */
    amount: number;
    /**
     * 
     * @type {Currency}
     * @memberof PriceDto
     */
    currency: Currency;
}



/**
 * Check if a given object implements the PriceDto interface.
 */
export function instanceOfPriceDto(value: object): value is PriceDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function PriceDtoFromJSON(json: any): PriceDto {
    return PriceDtoFromJSONTyped(json, false);
}

export function PriceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'currency': CurrencyFromJSON(json['currency']),
    };
}

export function PriceDtoToJSON(json: any): PriceDto {
    return PriceDtoToJSONTyped(json, false);
}

export function PriceDtoToJSONTyped(value?: PriceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currency': CurrencyToJSON(value['currency']),
    };
}

