/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublishTripRequestDto
 */
export interface PublishTripRequestDto {
    /**
     * 
     * @type {number}
     * @memberof PublishTripRequestDto
     */
    tripId: number;
}

/**
 * Check if a given object implements the PublishTripRequestDto interface.
 */
export function instanceOfPublishTripRequestDto(value: object): value is PublishTripRequestDto {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    return true;
}

export function PublishTripRequestDtoFromJSON(json: any): PublishTripRequestDto {
    return PublishTripRequestDtoFromJSONTyped(json, false);
}

export function PublishTripRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishTripRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
    };
}

export function PublishTripRequestDtoToJSON(json: any): PublishTripRequestDto {
    return PublishTripRequestDtoToJSONTyped(json, false);
}

export function PublishTripRequestDtoToJSONTyped(value?: PublishTripRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
    };
}

