/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshTokenRequestDto
 */
export interface RefreshTokenRequestDto {
    /**
     * 
     * @type {string}
     * @memberof RefreshTokenRequestDto
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the RefreshTokenRequestDto interface.
 */
export function instanceOfRefreshTokenRequestDto(value: object): value is RefreshTokenRequestDto {
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function RefreshTokenRequestDtoFromJSON(json: any): RefreshTokenRequestDto {
    return RefreshTokenRequestDtoFromJSONTyped(json, false);
}

export function RefreshTokenRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTokenRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'],
    };
}

export function RefreshTokenRequestDtoToJSON(json: any): RefreshTokenRequestDto {
    return RefreshTokenRequestDtoToJSONTyped(json, false);
}

export function RefreshTokenRequestDtoToJSONTyped(value?: RefreshTokenRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refreshToken': value['refreshToken'],
    };
}

