/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRole } from './UserRole';
import {
    UserRoleFromJSON,
    UserRoleFromJSONTyped,
    UserRoleToJSON,
    UserRoleToJSONTyped,
} from './UserRole';

/**
 * 
 * @export
 * @interface RegistrationUserRequestDto
 */
export interface RegistrationUserRequestDto {
    /**
     * 
     * @type {string}
     * @memberof RegistrationUserRequestDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationUserRequestDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationUserRequestDto
     */
    confirmPassword: string;
    /**
     * 
     * @type {UserRole}
     * @memberof RegistrationUserRequestDto
     */
    role: UserRole;
}



/**
 * Check if a given object implements the RegistrationUserRequestDto interface.
 */
export function instanceOfRegistrationUserRequestDto(value: object): value is RegistrationUserRequestDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('confirmPassword' in value) || value['confirmPassword'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function RegistrationUserRequestDtoFromJSON(json: any): RegistrationUserRequestDto {
    return RegistrationUserRequestDtoFromJSONTyped(json, false);
}

export function RegistrationUserRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationUserRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'confirmPassword': json['confirmPassword'],
        'role': UserRoleFromJSON(json['role']),
    };
}

export function RegistrationUserRequestDtoToJSON(json: any): RegistrationUserRequestDto {
    return RegistrationUserRequestDtoToJSONTyped(json, false);
}

export function RegistrationUserRequestDtoToJSONTyped(value?: RegistrationUserRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'confirmPassword': value['confirmPassword'],
        'role': UserRoleToJSON(value['role']),
    };
}

