/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ReviewTargetType = {
    USER: 'User',
    PLATFORM: 'Platform'
} as const;
export type ReviewTargetType = typeof ReviewTargetType[keyof typeof ReviewTargetType];


export function instanceOfReviewTargetType(value: any): boolean {
    for (const key in ReviewTargetType) {
        if (Object.prototype.hasOwnProperty.call(ReviewTargetType, key)) {
            if (ReviewTargetType[key as keyof typeof ReviewTargetType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReviewTargetTypeFromJSON(json: any): ReviewTargetType {
    return ReviewTargetTypeFromJSONTyped(json, false);
}

export function ReviewTargetTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewTargetType {
    return json as ReviewTargetType;
}

export function ReviewTargetTypeToJSON(value?: ReviewTargetType | null): any {
    return value as any;
}

export function ReviewTargetTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ReviewTargetType {
    return value as ReviewTargetType;
}

