/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewCriterionType } from './ReviewCriterionType';
import {
    ReviewCriterionTypeFromJSON,
    ReviewCriterionTypeFromJSONTyped,
    ReviewCriterionTypeToJSON,
    ReviewCriterionTypeToJSONTyped,
} from './ReviewCriterionType';

/**
 * 
 * @export
 * @interface ReviewDetailResponseDto
 */
export interface ReviewDetailResponseDto {
    /**
     * 
     * @type {ReviewCriterionType}
     * @memberof ReviewDetailResponseDto
     */
    criterion: ReviewCriterionType;
    /**
     * 
     * @type {number}
     * @memberof ReviewDetailResponseDto
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewDetailResponseDto
     */
    comment: string;
}



/**
 * Check if a given object implements the ReviewDetailResponseDto interface.
 */
export function instanceOfReviewDetailResponseDto(value: object): value is ReviewDetailResponseDto {
    if (!('criterion' in value) || value['criterion'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function ReviewDetailResponseDtoFromJSON(json: any): ReviewDetailResponseDto {
    return ReviewDetailResponseDtoFromJSONTyped(json, false);
}

export function ReviewDetailResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewDetailResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'criterion': ReviewCriterionTypeFromJSON(json['criterion']),
        'rating': json['rating'],
        'comment': json['comment'],
    };
}

export function ReviewDetailResponseDtoToJSON(json: any): ReviewDetailResponseDto {
    return ReviewDetailResponseDtoToJSONTyped(json, false);
}

export function ReviewDetailResponseDtoToJSONTyped(value?: ReviewDetailResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'criterion': ReviewCriterionTypeToJSON(value['criterion']),
        'rating': value['rating'],
        'comment': value['comment'],
    };
}

