/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailReviewRequestDto } from './DetailReviewRequestDto';
import {
    DetailReviewRequestDtoFromJSON,
    DetailReviewRequestDtoFromJSONTyped,
    DetailReviewRequestDtoToJSON,
    DetailReviewRequestDtoToJSONTyped,
} from './DetailReviewRequestDto';

/**
 * 
 * @export
 * @interface ReviewRequestDto
 */
export interface ReviewRequestDto {
    /**
     * 
     * @type {number}
     * @memberof ReviewRequestDto
     */
    overallRating: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewRequestDto
     */
    comment?: string | null;
    /**
     * 
     * @type {Array<DetailReviewRequestDto>}
     * @memberof ReviewRequestDto
     */
    details: Array<DetailReviewRequestDto>;
}

/**
 * Check if a given object implements the ReviewRequestDto interface.
 */
export function instanceOfReviewRequestDto(value: object): value is ReviewRequestDto {
    if (!('overallRating' in value) || value['overallRating'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function ReviewRequestDtoFromJSON(json: any): ReviewRequestDto {
    return ReviewRequestDtoFromJSONTyped(json, false);
}

export function ReviewRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'overallRating': json['overallRating'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'details': ((json['details'] as Array<any>).map(DetailReviewRequestDtoFromJSON)),
    };
}

export function ReviewRequestDtoToJSON(json: any): ReviewRequestDto {
    return ReviewRequestDtoToJSONTyped(json, false);
}

export function ReviewRequestDtoToJSONTyped(value?: ReviewRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'overallRating': value['overallRating'],
        'comment': value['comment'],
        'details': ((value['details'] as Array<any>).map(DetailReviewRequestDtoToJSON)),
    };
}

