/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RouteRequestDto } from './RouteRequestDto';
import {
    RouteRequestDtoFromJSON,
    RouteRequestDtoFromJSONTyped,
    RouteRequestDtoToJSON,
    RouteRequestDtoToJSONTyped,
} from './RouteRequestDto';
import type { Amenities } from './Amenities';
import {
    AmenitiesFromJSON,
    AmenitiesFromJSONTyped,
    AmenitiesToJSON,
    AmenitiesToJSONTyped,
} from './Amenities';

/**
 * 
 * @export
 * @interface SaveTripRequestDto
 */
export interface SaveTripRequestDto {
    /**
     * 
     * @type {number}
     * @memberof SaveTripRequestDto
     */
    tripId?: number | null;
    /**
     * 
     * @type {Array<RouteRequestDto>}
     * @memberof SaveTripRequestDto
     */
    routes?: Array<RouteRequestDto> | null;
    /**
     * 
     * @type {number}
     * @memberof SaveTripRequestDto
     */
    numberOfPersons?: number | null;
    /**
     * 
     * @type {Array<Amenities>}
     * @memberof SaveTripRequestDto
     */
    amenities?: Array<Amenities> | null;
    /**
     * 
     * @type {number}
     * @memberof SaveTripRequestDto
     */
    handicappedUserCount?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof SaveTripRequestDto
     */
    dietForTransporter?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof SaveTripRequestDto
     */
    endOrder?: Date | null;
}

/**
 * Check if a given object implements the SaveTripRequestDto interface.
 */
export function instanceOfSaveTripRequestDto(value: object): value is SaveTripRequestDto {
    return true;
}

export function SaveTripRequestDtoFromJSON(json: any): SaveTripRequestDto {
    return SaveTripRequestDtoFromJSONTyped(json, false);
}

export function SaveTripRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveTripRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'] == null ? undefined : json['tripId'],
        'routes': json['routes'] == null ? undefined : ((json['routes'] as Array<any>).map(RouteRequestDtoFromJSON)),
        'numberOfPersons': json['numberOfPersons'] == null ? undefined : json['numberOfPersons'],
        'amenities': json['amenities'] == null ? undefined : ((json['amenities'] as Array<any>).map(AmenitiesFromJSON)),
        'handicappedUserCount': json['handicappedUserCount'] == null ? undefined : json['handicappedUserCount'],
        'dietForTransporter': json['dietForTransporter'] == null ? undefined : json['dietForTransporter'],
        'endOrder': json['endOrder'] == null ? undefined : (new Date(json['endOrder'])),
    };
}

export function SaveTripRequestDtoToJSON(json: any): SaveTripRequestDto {
    return SaveTripRequestDtoToJSONTyped(json, false);
}

export function SaveTripRequestDtoToJSONTyped(value?: SaveTripRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
        'routes': value['routes'] == null ? undefined : ((value['routes'] as Array<any>).map(RouteRequestDtoToJSON)),
        'numberOfPersons': value['numberOfPersons'],
        'amenities': value['amenities'] == null ? undefined : ((value['amenities'] as Array<any>).map(AmenitiesToJSON)),
        'handicappedUserCount': value['handicappedUserCount'],
        'dietForTransporter': value['dietForTransporter'],
        'endOrder': value['endOrder'] == null ? value['endOrder'] : value['endOrder'].toISOString(),
    };
}

