/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendWarningForRestPayOrderRequestDto
 */
export interface SendWarningForRestPayOrderRequestDto {
    /**
     * 
     * @type {number}
     * @memberof SendWarningForRestPayOrderRequestDto
     */
    tripId: number;
}

/**
 * Check if a given object implements the SendWarningForRestPayOrderRequestDto interface.
 */
export function instanceOfSendWarningForRestPayOrderRequestDto(value: object): value is SendWarningForRestPayOrderRequestDto {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    return true;
}

export function SendWarningForRestPayOrderRequestDtoFromJSON(json: any): SendWarningForRestPayOrderRequestDto {
    return SendWarningForRestPayOrderRequestDtoFromJSONTyped(json, false);
}

export function SendWarningForRestPayOrderRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendWarningForRestPayOrderRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
    };
}

export function SendWarningForRestPayOrderRequestDtoToJSON(json: any): SendWarningForRestPayOrderRequestDto {
    return SendWarningForRestPayOrderRequestDtoToJSONTyped(json, false);
}

export function SendWarningForRestPayOrderRequestDtoToJSONTyped(value?: SendWarningForRestPayOrderRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
    };
}

