/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendWarningForPayOrderRequestDto
 */
export interface SendWarningForPayOrderRequestDto {
    /**
     * 
     * @type {number}
     * @memberof SendWarningForPayOrderRequestDto
     */
    tripId: number;
}

/**
 * Check if a given object implements the SendWarningForPayOrderRequestDto interface.
 */
export function instanceOfSendWarningForPayOrderRequestDto(value: object): value is SendWarningForPayOrderRequestDto {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    return true;
}

export function SendWarningForPayOrderRequestDtoFromJSON(json: any): SendWarningForPayOrderRequestDto {
    return SendWarningForPayOrderRequestDtoFromJSONTyped(json, false);
}

export function SendWarningForPayOrderRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendWarningForPayOrderRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
    };
}

export function SendWarningForPayOrderRequestDtoToJSON(json: any): SendWarningForPayOrderRequestDto {
    return SendWarningForPayOrderRequestDtoToJSONTyped(json, false);
}

export function SendWarningForPayOrderRequestDtoToJSONTyped(value?: SendWarningForPayOrderRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
    };
}

