/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartTripRequestDto
 */
export interface StartTripRequestDto {
    /**
     * 
     * @type {number}
     * @memberof StartTripRequestDto
     */
    tripId: number;
}

/**
 * Check if a given object implements the StartTripRequestDto interface.
 */
export function instanceOfStartTripRequestDto(value: object): value is StartTripRequestDto {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    return true;
}

export function StartTripRequestDtoFromJSON(json: any): StartTripRequestDto {
    return StartTripRequestDtoFromJSONTyped(json, false);
}

export function StartTripRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartTripRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
    };
}

export function StartTripRequestDtoToJSON(json: any): StartTripRequestDto {
    return StartTripRequestDtoToJSONTyped(json, false);
}

export function StartTripRequestDtoToJSONTyped(value?: StartTripRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
    };
}

