/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewRequestDto } from './ReviewRequestDto';
import {
    ReviewRequestDtoFromJSON,
    ReviewRequestDtoFromJSONTyped,
    ReviewRequestDtoToJSON,
    ReviewRequestDtoToJSONTyped,
} from './ReviewRequestDto';

/**
 * 
 * @export
 * @interface SubmitReviewRequestDto
 */
export interface SubmitReviewRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SubmitReviewRequestDto
     */
    token: string;
    /**
     * 
     * @type {ReviewRequestDto}
     * @memberof SubmitReviewRequestDto
     */
    userReview: ReviewRequestDto;
    /**
     * 
     * @type {ReviewRequestDto}
     * @memberof SubmitReviewRequestDto
     */
    platformReview: ReviewRequestDto;
}

/**
 * Check if a given object implements the SubmitReviewRequestDto interface.
 */
export function instanceOfSubmitReviewRequestDto(value: object): value is SubmitReviewRequestDto {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('userReview' in value) || value['userReview'] === undefined) return false;
    if (!('platformReview' in value) || value['platformReview'] === undefined) return false;
    return true;
}

export function SubmitReviewRequestDtoFromJSON(json: any): SubmitReviewRequestDto {
    return SubmitReviewRequestDtoFromJSONTyped(json, false);
}

export function SubmitReviewRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitReviewRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'userReview': ReviewRequestDtoFromJSON(json['userReview']),
        'platformReview': ReviewRequestDtoFromJSON(json['platformReview']),
    };
}

export function SubmitReviewRequestDtoToJSON(json: any): SubmitReviewRequestDto {
    return SubmitReviewRequestDtoToJSONTyped(json, false);
}

export function SubmitReviewRequestDtoToJSONTyped(value?: SubmitReviewRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'userReview': ReviewRequestDtoToJSON(value['userReview']),
        'platformReview': ReviewRequestDtoToJSON(value['platformReview']),
    };
}

