/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransportRequirementsType } from './TransportRequirementsType';
import {
    TransportRequirementsTypeFromJSON,
    TransportRequirementsTypeFromJSONTyped,
    TransportRequirementsTypeToJSON,
    TransportRequirementsTypeToJSONTyped,
} from './TransportRequirementsType';
import type { FileResponseDto } from './FileResponseDto';
import {
    FileResponseDtoFromJSON,
    FileResponseDtoFromJSONTyped,
    FileResponseDtoToJSON,
    FileResponseDtoToJSONTyped,
} from './FileResponseDto';

/**
 * 
 * @export
 * @interface TransportDocumentResponseDto
 */
export interface TransportDocumentResponseDto {
    /**
     * 
     * @type {number}
     * @memberof TransportDocumentResponseDto
     */
    id: number;
    /**
     * 
     * @type {TransportRequirementsType}
     * @memberof TransportDocumentResponseDto
     */
    type: TransportRequirementsType;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof TransportDocumentResponseDto
     */
    file?: FileResponseDto;
}



/**
 * Check if a given object implements the TransportDocumentResponseDto interface.
 */
export function instanceOfTransportDocumentResponseDto(value: object): value is TransportDocumentResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TransportDocumentResponseDtoFromJSON(json: any): TransportDocumentResponseDto {
    return TransportDocumentResponseDtoFromJSONTyped(json, false);
}

export function TransportDocumentResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportDocumentResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': TransportRequirementsTypeFromJSON(json['type']),
        'file': json['file'] == null ? undefined : FileResponseDtoFromJSON(json['file']),
    };
}

export function TransportDocumentResponseDtoToJSON(json: any): TransportDocumentResponseDto {
    return TransportDocumentResponseDtoToJSONTyped(json, false);
}

export function TransportDocumentResponseDtoToJSONTyped(value?: TransportDocumentResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': TransportRequirementsTypeToJSON(value['type']),
        'file': FileResponseDtoToJSON(value['file']),
    };
}

