/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileResponseDto } from './FileResponseDto';
import {
    FileResponseDtoFromJSON,
    FileResponseDtoFromJSONTyped,
    FileResponseDtoToJSON,
    FileResponseDtoToJSONTyped,
} from './FileResponseDto';

/**
 * 
 * @export
 * @interface TransporterRequirementsResponseDto
 */
export interface TransporterRequirementsResponseDto {
    /**
     * 
     * @type {string}
     * @memberof TransporterRequirementsResponseDto
     */
    concessionNumber?: string | null;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof TransporterRequirementsResponseDto
     */
    concessionDocuments?: FileResponseDto;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof TransporterRequirementsResponseDto
     */
    businessRiskInsurance?: FileResponseDto;
}

/**
 * Check if a given object implements the TransporterRequirementsResponseDto interface.
 */
export function instanceOfTransporterRequirementsResponseDto(value: object): value is TransporterRequirementsResponseDto {
    return true;
}

export function TransporterRequirementsResponseDtoFromJSON(json: any): TransporterRequirementsResponseDto {
    return TransporterRequirementsResponseDtoFromJSONTyped(json, false);
}

export function TransporterRequirementsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransporterRequirementsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'concessionNumber': json['concessionNumber'] == null ? undefined : json['concessionNumber'],
        'concessionDocuments': json['concessionDocuments'] == null ? undefined : FileResponseDtoFromJSON(json['concessionDocuments']),
        'businessRiskInsurance': json['businessRiskInsurance'] == null ? undefined : FileResponseDtoFromJSON(json['businessRiskInsurance']),
    };
}

export function TransporterRequirementsResponseDtoToJSON(json: any): TransporterRequirementsResponseDto {
    return TransporterRequirementsResponseDtoToJSONTyped(json, false);
}

export function TransporterRequirementsResponseDtoToJSONTyped(value?: TransporterRequirementsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'concessionNumber': value['concessionNumber'],
        'concessionDocuments': FileResponseDtoToJSON(value['concessionDocuments']),
        'businessRiskInsurance': FileResponseDtoToJSON(value['businessRiskInsurance']),
    };
}

