/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadTransportDocumentItemRequestDto } from './UploadTransportDocumentItemRequestDto';
import {
    UploadTransportDocumentItemRequestDtoFromJSON,
    UploadTransportDocumentItemRequestDtoFromJSONTyped,
    UploadTransportDocumentItemRequestDtoToJSON,
    UploadTransportDocumentItemRequestDtoToJSONTyped,
} from './UploadTransportDocumentItemRequestDto';

/**
 * 
 * @export
 * @interface TransportRequirementsCreateUploadUrlFilesRequestDto
 */
export interface TransportRequirementsCreateUploadUrlFilesRequestDto {
    /**
     * 
     * @type {number}
     * @memberof TransportRequirementsCreateUploadUrlFilesRequestDto
     */
    requirementsId: number;
    /**
     * 
     * @type {Array<UploadTransportDocumentItemRequestDto>}
     * @memberof TransportRequirementsCreateUploadUrlFilesRequestDto
     */
    documents: Array<UploadTransportDocumentItemRequestDto>;
}

/**
 * Check if a given object implements the TransportRequirementsCreateUploadUrlFilesRequestDto interface.
 */
export function instanceOfTransportRequirementsCreateUploadUrlFilesRequestDto(value: object): value is TransportRequirementsCreateUploadUrlFilesRequestDto {
    if (!('requirementsId' in value) || value['requirementsId'] === undefined) return false;
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function TransportRequirementsCreateUploadUrlFilesRequestDtoFromJSON(json: any): TransportRequirementsCreateUploadUrlFilesRequestDto {
    return TransportRequirementsCreateUploadUrlFilesRequestDtoFromJSONTyped(json, false);
}

export function TransportRequirementsCreateUploadUrlFilesRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportRequirementsCreateUploadUrlFilesRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'requirementsId': json['requirementsId'],
        'documents': ((json['documents'] as Array<any>).map(UploadTransportDocumentItemRequestDtoFromJSON)),
    };
}

export function TransportRequirementsCreateUploadUrlFilesRequestDtoToJSON(json: any): TransportRequirementsCreateUploadUrlFilesRequestDto {
    return TransportRequirementsCreateUploadUrlFilesRequestDtoToJSONTyped(json, false);
}

export function TransportRequirementsCreateUploadUrlFilesRequestDtoToJSONTyped(value?: TransportRequirementsCreateUploadUrlFilesRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requirementsId': value['requirementsId'],
        'documents': ((value['documents'] as Array<any>).map(UploadTransportDocumentItemRequestDtoToJSON)),
    };
}

