/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadSasUrlResponseDto } from './UploadSasUrlResponseDto';
import {
    UploadSasUrlResponseDtoFromJSON,
    UploadSasUrlResponseDtoFromJSONTyped,
    UploadSasUrlResponseDtoToJSON,
    UploadSasUrlResponseDtoToJSONTyped,
} from './UploadSasUrlResponseDto';

/**
 * 
 * @export
 * @interface TransportRequirementsUploadSasUrlResponseDto
 */
export interface TransportRequirementsUploadSasUrlResponseDto {
    /**
     * 
     * @type {Array<UploadSasUrlResponseDto>}
     * @memberof TransportRequirementsUploadSasUrlResponseDto
     */
    documents: Array<UploadSasUrlResponseDto>;
}

/**
 * Check if a given object implements the TransportRequirementsUploadSasUrlResponseDto interface.
 */
export function instanceOfTransportRequirementsUploadSasUrlResponseDto(value: object): value is TransportRequirementsUploadSasUrlResponseDto {
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function TransportRequirementsUploadSasUrlResponseDtoFromJSON(json: any): TransportRequirementsUploadSasUrlResponseDto {
    return TransportRequirementsUploadSasUrlResponseDtoFromJSONTyped(json, false);
}

export function TransportRequirementsUploadSasUrlResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportRequirementsUploadSasUrlResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'documents': ((json['documents'] as Array<any>).map(UploadSasUrlResponseDtoFromJSON)),
    };
}

export function TransportRequirementsUploadSasUrlResponseDtoToJSON(json: any): TransportRequirementsUploadSasUrlResponseDto {
    return TransportRequirementsUploadSasUrlResponseDtoToJSONTyped(json, false);
}

export function TransportRequirementsUploadSasUrlResponseDtoToJSONTyped(value?: TransportRequirementsUploadSasUrlResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'documents': ((value['documents'] as Array<any>).map(UploadSasUrlResponseDtoToJSON)),
    };
}

