/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransportDocumentResponseDto } from './TransportDocumentResponseDto';
import {
    TransportDocumentResponseDtoFromJSON,
    TransportDocumentResponseDtoFromJSONTyped,
    TransportDocumentResponseDtoToJSON,
    TransportDocumentResponseDtoToJSONTyped,
} from './TransportDocumentResponseDto';

/**
 * 
 * @export
 * @interface TransporterRequirementsResponseDto
 */
export interface TransporterRequirementsResponseDto {
    /**
     * 
     * @type {string}
     * @memberof TransporterRequirementsResponseDto
     */
    concessionNumber?: string | null;
    /**
     * 
     * @type {Array<TransportDocumentResponseDto>}
     * @memberof TransporterRequirementsResponseDto
     */
    documents: Array<TransportDocumentResponseDto>;
}

/**
 * Check if a given object implements the TransporterRequirementsResponseDto interface.
 */
export function instanceOfTransporterRequirementsResponseDto(value: object): value is TransporterRequirementsResponseDto {
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function TransporterRequirementsResponseDtoFromJSON(json: any): TransporterRequirementsResponseDto {
    return TransporterRequirementsResponseDtoFromJSONTyped(json, false);
}

export function TransporterRequirementsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransporterRequirementsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'concessionNumber': json['concessionNumber'] == null ? undefined : json['concessionNumber'],
        'documents': ((json['documents'] as Array<any>).map(TransportDocumentResponseDtoFromJSON)),
    };
}

export function TransporterRequirementsResponseDtoToJSON(json: any): TransporterRequirementsResponseDto {
    return TransporterRequirementsResponseDtoToJSONTyped(json, false);
}

export function TransporterRequirementsResponseDtoToJSONTyped(value?: TransporterRequirementsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'concessionNumber': value['concessionNumber'],
        'documents': ((value['documents'] as Array<any>).map(TransportDocumentResponseDtoToJSON)),
    };
}

