/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransportRequirementsVerificationRequestDto
 */
export interface TransportRequirementsVerificationRequestDto {
    /**
     * 
     * @type {number}
     * @memberof TransportRequirementsVerificationRequestDto
     */
    requirementsId: number;
    /**
     * 
     * @type {boolean}
     * @memberof TransportRequirementsVerificationRequestDto
     */
    isVerified: boolean;
    /**
     * 
     * @type {string}
     * @memberof TransportRequirementsVerificationRequestDto
     */
    description?: string | null;
}

/**
 * Check if a given object implements the TransportRequirementsVerificationRequestDto interface.
 */
export function instanceOfTransportRequirementsVerificationRequestDto(value: object): value is TransportRequirementsVerificationRequestDto {
    if (!('requirementsId' in value) || value['requirementsId'] === undefined) return false;
    if (!('isVerified' in value) || value['isVerified'] === undefined) return false;
    return true;
}

export function TransportRequirementsVerificationRequestDtoFromJSON(json: any): TransportRequirementsVerificationRequestDto {
    return TransportRequirementsVerificationRequestDtoFromJSONTyped(json, false);
}

export function TransportRequirementsVerificationRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportRequirementsVerificationRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'requirementsId': json['requirementsId'],
        'isVerified': json['isVerified'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function TransportRequirementsVerificationRequestDtoToJSON(json: any): TransportRequirementsVerificationRequestDto {
    return TransportRequirementsVerificationRequestDtoToJSONTyped(json, false);
}

export function TransportRequirementsVerificationRequestDtoToJSONTyped(value?: TransportRequirementsVerificationRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requirementsId': value['requirementsId'],
        'isVerified': value['isVerified'],
        'description': value['description'],
    };
}

