/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransportRequirementsSendToVerificationRequestDto
 */
export interface TransportRequirementsSendToVerificationRequestDto {
    /**
     * 
     * @type {number}
     * @memberof TransportRequirementsSendToVerificationRequestDto
     */
    requirementsId: number;
}

/**
 * Check if a given object implements the TransportRequirementsSendToVerificationRequestDto interface.
 */
export function instanceOfTransportRequirementsSendToVerificationRequestDto(value: object): value is TransportRequirementsSendToVerificationRequestDto {
    if (!('requirementsId' in value) || value['requirementsId'] === undefined) return false;
    return true;
}

export function TransportRequirementsSendToVerificationRequestDtoFromJSON(json: any): TransportRequirementsSendToVerificationRequestDto {
    return TransportRequirementsSendToVerificationRequestDtoFromJSONTyped(json, false);
}

export function TransportRequirementsSendToVerificationRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportRequirementsSendToVerificationRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'requirementsId': json['requirementsId'],
    };
}

export function TransportRequirementsSendToVerificationRequestDtoToJSON(json: any): TransportRequirementsSendToVerificationRequestDto {
    return TransportRequirementsSendToVerificationRequestDtoToJSONTyped(json, false);
}

export function TransportRequirementsSendToVerificationRequestDtoToJSONTyped(value?: TransportRequirementsSendToVerificationRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requirementsId': value['requirementsId'],
    };
}

