/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TripOfferCloseReason = {
    UNPAID: 'UNPAID',
    NO_TRANSPORTER: 'NO_TRANSPORTER'
} as const;
export type TripOfferCloseReason = typeof TripOfferCloseReason[keyof typeof TripOfferCloseReason];


export function instanceOfTripOfferCloseReason(value: any): boolean {
    for (const key in TripOfferCloseReason) {
        if (Object.prototype.hasOwnProperty.call(TripOfferCloseReason, key)) {
            if (TripOfferCloseReason[key as keyof typeof TripOfferCloseReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TripOfferCloseReasonFromJSON(json: any): TripOfferCloseReason {
    return TripOfferCloseReasonFromJSONTyped(json, false);
}

export function TripOfferCloseReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripOfferCloseReason {
    return json as TripOfferCloseReason;
}

export function TripOfferCloseReasonToJSON(value?: TripOfferCloseReason | null): any {
    return value as any;
}

export function TripOfferCloseReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): TripOfferCloseReason {
    return value as TripOfferCloseReason;
}

