/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TripOfferAcceptMethod = {
    PAY_DEPOSIT: 'PAY_DEPOSIT',
    PAY_FULL: 'PAY_FULL'
} as const;
export type TripOfferAcceptMethod = typeof TripOfferAcceptMethod[keyof typeof TripOfferAcceptMethod];


export function instanceOfTripOfferAcceptMethod(value: any): boolean {
    for (const key in TripOfferAcceptMethod) {
        if (Object.prototype.hasOwnProperty.call(TripOfferAcceptMethod, key)) {
            if (TripOfferAcceptMethod[key as keyof typeof TripOfferAcceptMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TripOfferAcceptMethodFromJSON(json: any): TripOfferAcceptMethod {
    return TripOfferAcceptMethodFromJSONTyped(json, false);
}

export function TripOfferAcceptMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripOfferAcceptMethod {
    return json as TripOfferAcceptMethod;
}

export function TripOfferAcceptMethodToJSON(value?: TripOfferAcceptMethod | null): any {
    return value as any;
}

export function TripOfferAcceptMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): TripOfferAcceptMethod {
    return value as TripOfferAcceptMethod;
}

