/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CloseTripOfferReason } from './CloseTripOfferReason';
import {
    CloseTripOfferReasonFromJSON,
    CloseTripOfferReasonFromJSONTyped,
    CloseTripOfferReasonToJSON,
    CloseTripOfferReasonToJSONTyped,
} from './CloseTripOfferReason';
import type { TripOfferState } from './TripOfferState';
import {
    TripOfferStateFromJSON,
    TripOfferStateFromJSONTyped,
    TripOfferStateToJSON,
    TripOfferStateToJSONTyped,
} from './TripOfferState';

/**
 * 
 * @export
 * @interface TripOfferMovementsResponseDto
 */
export interface TripOfferMovementsResponseDto {
    /**
     * 
     * @type {number}
     * @memberof TripOfferMovementsResponseDto
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TripOfferMovementsResponseDto
     */
    tripId: number;
    /**
     * 
     * @type {TripOfferState}
     * @memberof TripOfferMovementsResponseDto
     */
    from: TripOfferState;
    /**
     * 
     * @type {TripOfferState}
     * @memberof TripOfferMovementsResponseDto
     */
    to: TripOfferState;
    /**
     * 
     * @type {Date}
     * @memberof TripOfferMovementsResponseDto
     */
    datetime: Date;
    /**
     * 
     * @type {CloseTripOfferReason}
     * @memberof TripOfferMovementsResponseDto
     */
    reason?: CloseTripOfferReason;
    /**
     * 
     * @type {string}
     * @memberof TripOfferMovementsResponseDto
     */
    customReason?: string | null;
}



/**
 * Check if a given object implements the TripOfferMovementsResponseDto interface.
 */
export function instanceOfTripOfferMovementsResponseDto(value: object): value is TripOfferMovementsResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('datetime' in value) || value['datetime'] === undefined) return false;
    return true;
}

export function TripOfferMovementsResponseDtoFromJSON(json: any): TripOfferMovementsResponseDto {
    return TripOfferMovementsResponseDtoFromJSONTyped(json, false);
}

export function TripOfferMovementsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripOfferMovementsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tripId': json['tripId'],
        'from': TripOfferStateFromJSON(json['from']),
        'to': TripOfferStateFromJSON(json['to']),
        'datetime': (new Date(json['datetime'])),
        'reason': json['reason'] == null ? undefined : CloseTripOfferReasonFromJSON(json['reason']),
        'customReason': json['customReason'] == null ? undefined : json['customReason'],
    };
}

export function TripOfferMovementsResponseDtoToJSON(json: any): TripOfferMovementsResponseDto {
    return TripOfferMovementsResponseDtoToJSONTyped(json, false);
}

export function TripOfferMovementsResponseDtoToJSONTyped(value?: TripOfferMovementsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tripId': value['tripId'],
        'from': TripOfferStateToJSON(value['from']),
        'to': TripOfferStateToJSON(value['to']),
        'datetime': value['datetime'].toISOString(),
        'reason': CloseTripOfferReasonToJSON(value['reason']),
        'customReason': value['customReason'],
    };
}

