/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TripBaseInfoItemResponseDto } from './TripBaseInfoItemResponseDto';
import {
    TripBaseInfoItemResponseDtoFromJSON,
    TripBaseInfoItemResponseDtoFromJSONTyped,
    TripBaseInfoItemResponseDtoToJSON,
    TripBaseInfoItemResponseDtoToJSONTyped,
} from './TripBaseInfoItemResponseDto';
import type { ReviewResponseDto } from './ReviewResponseDto';
import {
    ReviewResponseDtoFromJSON,
    ReviewResponseDtoFromJSONTyped,
    ReviewResponseDtoToJSON,
    ReviewResponseDtoToJSONTyped,
} from './ReviewResponseDto';

/**
 * 
 * @export
 * @interface TripReviewResponseDto
 */
export interface TripReviewResponseDto {
    /**
     * 
     * @type {TripBaseInfoItemResponseDto}
     * @memberof TripReviewResponseDto
     */
    trip: TripBaseInfoItemResponseDto;
    /**
     * 
     * @type {ReviewResponseDto}
     * @memberof TripReviewResponseDto
     */
    userReview: ReviewResponseDto;
    /**
     * 
     * @type {ReviewResponseDto}
     * @memberof TripReviewResponseDto
     */
    platformReview: ReviewResponseDto;
}

/**
 * Check if a given object implements the TripReviewResponseDto interface.
 */
export function instanceOfTripReviewResponseDto(value: object): value is TripReviewResponseDto {
    if (!('trip' in value) || value['trip'] === undefined) return false;
    if (!('userReview' in value) || value['userReview'] === undefined) return false;
    if (!('platformReview' in value) || value['platformReview'] === undefined) return false;
    return true;
}

export function TripReviewResponseDtoFromJSON(json: any): TripReviewResponseDto {
    return TripReviewResponseDtoFromJSONTyped(json, false);
}

export function TripReviewResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripReviewResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'trip': TripBaseInfoItemResponseDtoFromJSON(json['trip']),
        'userReview': ReviewResponseDtoFromJSON(json['userReview']),
        'platformReview': ReviewResponseDtoFromJSON(json['platformReview']),
    };
}

export function TripReviewResponseDtoToJSON(json: any): TripReviewResponseDto {
    return TripReviewResponseDtoToJSONTyped(json, false);
}

export function TripReviewResponseDtoToJSONTyped(value?: TripReviewResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trip': TripBaseInfoItemResponseDtoToJSON(value['trip']),
        'userReview': ReviewResponseDtoToJSON(value['userReview']),
        'platformReview': ReviewResponseDtoToJSON(value['platformReview']),
    };
}

