/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TripReviewDataResponseDto } from './TripReviewDataResponseDto';
import {
    TripReviewDataResponseDtoFromJSON,
    TripReviewDataResponseDtoFromJSONTyped,
    TripReviewDataResponseDtoToJSON,
    TripReviewDataResponseDtoToJSONTyped,
} from './TripReviewDataResponseDto';

/**
 * 
 * @export
 * @interface TripReviewResponseDto
 */
export interface TripReviewResponseDto {
    /**
     * 
     * @type {TripReviewDataResponseDto}
     * @memberof TripReviewResponseDto
     */
    result?: TripReviewDataResponseDto;
}

/**
 * Check if a given object implements the TripReviewResponseDto interface.
 */
export function instanceOfTripReviewResponseDto(value: object): value is TripReviewResponseDto {
    return true;
}

export function TripReviewResponseDtoFromJSON(json: any): TripReviewResponseDto {
    return TripReviewResponseDtoFromJSONTyped(json, false);
}

export function TripReviewResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripReviewResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : TripReviewDataResponseDtoFromJSON(json['result']),
    };
}

export function TripReviewResponseDtoToJSON(json: any): TripReviewResponseDto {
    return TripReviewResponseDtoToJSONTyped(json, false);
}

export function TripReviewResponseDtoToJSONTyped(value?: TripReviewResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': TripReviewDataResponseDtoToJSON(value['result']),
    };
}

