/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TripOfferChange = {
    PAYED: 'PAYED',
    CLOSE: 'CLOSE'
} as const;
export type TripOfferChange = typeof TripOfferChange[keyof typeof TripOfferChange];


export function instanceOfTripOfferChange(value: any): boolean {
    for (const key in TripOfferChange) {
        if (Object.prototype.hasOwnProperty.call(TripOfferChange, key)) {
            if (TripOfferChange[key as keyof typeof TripOfferChange] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TripOfferChangeFromJSON(json: any): TripOfferChange {
    return TripOfferChangeFromJSONTyped(json, false);
}

export function TripOfferChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripOfferChange {
    return json as TripOfferChange;
}

export function TripOfferChangeToJSON(value?: TripOfferChange | null): any {
    return value as any;
}

export function TripOfferChangeToJSONTyped(value: any, ignoreDiscriminator: boolean): TripOfferChange {
    return value as TripOfferChange;
}

