/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceDto } from './PriceDto';
import {
    PriceDtoFromJSON,
    PriceDtoFromJSONTyped,
    PriceDtoToJSON,
    PriceDtoToJSONTyped,
} from './PriceDto';
import type { TripInvoicePayType } from './TripInvoicePayType';
import {
    TripInvoicePayTypeFromJSON,
    TripInvoicePayTypeFromJSONTyped,
    TripInvoicePayTypeToJSON,
    TripInvoicePayTypeToJSONTyped,
} from './TripInvoicePayType';
import type { InvoiceType } from './InvoiceType';
import {
    InvoiceTypeFromJSON,
    InvoiceTypeFromJSONTyped,
    InvoiceTypeToJSON,
    InvoiceTypeToJSONTyped,
} from './InvoiceType';

/**
 * 
 * @export
 * @interface TripInvoiceResponseDto
 */
export interface TripInvoiceResponseDto {
    /**
     * 
     * @type {number}
     * @memberof TripInvoiceResponseDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TripInvoiceResponseDto
     */
    variableSymbol: string;
    /**
     * 
     * @type {Date}
     * @memberof TripInvoiceResponseDto
     */
    dateOfIssue: Date;
    /**
     * 
     * @type {Date}
     * @memberof TripInvoiceResponseDto
     */
    dueDate: Date;
    /**
     * 
     * @type {InvoiceType}
     * @memberof TripInvoiceResponseDto
     */
    type: InvoiceType;
    /**
     * 
     * @type {PriceDto}
     * @memberof TripInvoiceResponseDto
     */
    price: PriceDto;
    /**
     * 
     * @type {boolean}
     * @memberof TripInvoiceResponseDto
     */
    payed: boolean;
    /**
     * 
     * @type {TripInvoicePayType}
     * @memberof TripInvoiceResponseDto
     */
    payType: TripInvoicePayType;
}



/**
 * Check if a given object implements the TripInvoiceResponseDto interface.
 */
export function instanceOfTripInvoiceResponseDto(value: object): value is TripInvoiceResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('variableSymbol' in value) || value['variableSymbol'] === undefined) return false;
    if (!('dateOfIssue' in value) || value['dateOfIssue'] === undefined) return false;
    if (!('dueDate' in value) || value['dueDate'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('payed' in value) || value['payed'] === undefined) return false;
    if (!('payType' in value) || value['payType'] === undefined) return false;
    return true;
}

export function TripInvoiceResponseDtoFromJSON(json: any): TripInvoiceResponseDto {
    return TripInvoiceResponseDtoFromJSONTyped(json, false);
}

export function TripInvoiceResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripInvoiceResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'variableSymbol': json['variableSymbol'],
        'dateOfIssue': (new Date(json['dateOfIssue'])),
        'dueDate': (new Date(json['dueDate'])),
        'type': InvoiceTypeFromJSON(json['type']),
        'price': PriceDtoFromJSON(json['price']),
        'payed': json['payed'],
        'payType': TripInvoicePayTypeFromJSON(json['payType']),
    };
}

export function TripInvoiceResponseDtoToJSON(json: any): TripInvoiceResponseDto {
    return TripInvoiceResponseDtoToJSONTyped(json, false);
}

export function TripInvoiceResponseDtoToJSONTyped(value?: TripInvoiceResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'variableSymbol': value['variableSymbol'],
        'dateOfIssue': ((value['dateOfIssue']).toISOString()),
        'dueDate': ((value['dueDate']).toISOString()),
        'type': InvoiceTypeToJSON(value['type']),
        'price': PriceDtoToJSON(value['price']),
        'payed': value['payed'],
        'payType': TripInvoicePayTypeToJSON(value['payType']),
    };
}

