/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EuroStandard } from './EuroStandard';
import {
    EuroStandardFromJSON,
    EuroStandardFromJSONTyped,
    EuroStandardToJSON,
    EuroStandardToJSONTyped,
} from './EuroStandard';
import type { PlaceRequestDto } from './PlaceRequestDto';
import {
    PlaceRequestDtoFromJSON,
    PlaceRequestDtoFromJSONTyped,
    PlaceRequestDtoToJSON,
    PlaceRequestDtoToJSONTyped,
} from './PlaceRequestDto';
import type { Amenities } from './Amenities';
import {
    AmenitiesFromJSON,
    AmenitiesFromJSONTyped,
    AmenitiesToJSON,
    AmenitiesToJSONTyped,
} from './Amenities';

/**
 * 
 * @export
 * @interface UpdateVehicleRequestDto
 */
export interface UpdateVehicleRequestDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateVehicleRequestDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateVehicleRequestDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateVehicleRequestDto
     */
    registrationSign: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateVehicleRequestDto
     */
    vin: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateVehicleRequestDto
     */
    stkExpired: Date;
    /**
     * 
     * @type {number}
     * @memberof UpdateVehicleRequestDto
     */
    yearOfManufacture: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateVehicleRequestDto
     */
    personsCapacity?: number | null;
    /**
     * 
     * @type {EuroStandard}
     * @memberof UpdateVehicleRequestDto
     */
    euro?: EuroStandard;
    /**
     * 
     * @type {Array<Amenities>}
     * @memberof UpdateVehicleRequestDto
     */
    amenities?: Array<Amenities> | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateVehicleRequestDto
     */
    handicappedUserCount?: number | null;
    /**
     * 
     * @type {PlaceRequestDto}
     * @memberof UpdateVehicleRequestDto
     */
    departureStation?: PlaceRequestDto;
}



/**
 * Check if a given object implements the UpdateVehicleRequestDto interface.
 */
export function instanceOfUpdateVehicleRequestDto(value: object): value is UpdateVehicleRequestDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('registrationSign' in value) || value['registrationSign'] === undefined) return false;
    if (!('vin' in value) || value['vin'] === undefined) return false;
    if (!('stkExpired' in value) || value['stkExpired'] === undefined) return false;
    if (!('yearOfManufacture' in value) || value['yearOfManufacture'] === undefined) return false;
    return true;
}

export function UpdateVehicleRequestDtoFromJSON(json: any): UpdateVehicleRequestDto {
    return UpdateVehicleRequestDtoFromJSONTyped(json, false);
}

export function UpdateVehicleRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateVehicleRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'registrationSign': json['registrationSign'],
        'vin': json['vin'],
        'stkExpired': (new Date(json['stkExpired'])),
        'yearOfManufacture': json['yearOfManufacture'],
        'personsCapacity': json['personsCapacity'] == null ? undefined : json['personsCapacity'],
        'euro': json['euro'] == null ? undefined : EuroStandardFromJSON(json['euro']),
        'amenities': json['amenities'] == null ? undefined : ((json['amenities'] as Array<any>).map(AmenitiesFromJSON)),
        'handicappedUserCount': json['handicappedUserCount'] == null ? undefined : json['handicappedUserCount'],
        'departureStation': json['departureStation'] == null ? undefined : PlaceRequestDtoFromJSON(json['departureStation']),
    };
}

export function UpdateVehicleRequestDtoToJSON(json: any): UpdateVehicleRequestDto {
    return UpdateVehicleRequestDtoToJSONTyped(json, false);
}

export function UpdateVehicleRequestDtoToJSONTyped(value?: UpdateVehicleRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'registrationSign': value['registrationSign'],
        'vin': value['vin'],
        'stkExpired': ((value['stkExpired']).toISOString()),
        'yearOfManufacture': value['yearOfManufacture'],
        'personsCapacity': value['personsCapacity'],
        'euro': EuroStandardToJSON(value['euro']),
        'amenities': value['amenities'] == null ? undefined : ((value['amenities'] as Array<any>).map(AmenitiesToJSON)),
        'handicappedUserCount': value['handicappedUserCount'],
        'departureStation': PlaceRequestDtoToJSON(value['departureStation']),
    };
}

