/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOfferRequestDto
 */
export interface UpdateOfferRequestDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateOfferRequestDto
     */
    offerId: number;
    /**
     * 
     * @type {Date}
     * @memberof UpdateOfferRequestDto
     */
    endOfferDate: Date;
}

/**
 * Check if a given object implements the UpdateOfferRequestDto interface.
 */
export function instanceOfUpdateOfferRequestDto(value: object): value is UpdateOfferRequestDto {
    if (!('offerId' in value) || value['offerId'] === undefined) return false;
    if (!('endOfferDate' in value) || value['endOfferDate'] === undefined) return false;
    return true;
}

export function UpdateOfferRequestDtoFromJSON(json: any): UpdateOfferRequestDto {
    return UpdateOfferRequestDtoFromJSONTyped(json, false);
}

export function UpdateOfferRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOfferRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'offerId': json['offerId'],
        'endOfferDate': (new Date(json['endOfferDate'])),
    };
}

export function UpdateOfferRequestDtoToJSON(json: any): UpdateOfferRequestDto {
    return UpdateOfferRequestDtoToJSONTyped(json, false);
}

export function UpdateOfferRequestDtoToJSONTyped(value?: UpdateOfferRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offerId': value['offerId'],
        'endOfferDate': ((value['endOfferDate']).toISOString()),
    };
}

