/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehiclePhotoType } from './VehiclePhotoType';
import {
    VehiclePhotoTypeFromJSON,
    VehiclePhotoTypeFromJSONTyped,
    VehiclePhotoTypeToJSON,
    VehiclePhotoTypeToJSONTyped,
} from './VehiclePhotoType';

/**
 * 
 * @export
 * @interface UploadPhotoItemRequestDto
 */
export interface UploadPhotoItemRequestDto {
    /**
     * 
     * @type {VehiclePhotoType}
     * @memberof UploadPhotoItemRequestDto
     */
    type: VehiclePhotoType;
    /**
     * 
     * @type {string}
     * @memberof UploadPhotoItemRequestDto
     */
    clientFileId: string;
    /**
     * 
     * @type {string}
     * @memberof UploadPhotoItemRequestDto
     */
    fileName: string;
}



/**
 * Check if a given object implements the UploadPhotoItemRequestDto interface.
 */
export function instanceOfUploadPhotoItemRequestDto(value: object): value is UploadPhotoItemRequestDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('clientFileId' in value) || value['clientFileId'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    return true;
}

export function UploadPhotoItemRequestDtoFromJSON(json: any): UploadPhotoItemRequestDto {
    return UploadPhotoItemRequestDtoFromJSONTyped(json, false);
}

export function UploadPhotoItemRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadPhotoItemRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': VehiclePhotoTypeFromJSON(json['type']),
        'clientFileId': json['clientFileId'],
        'fileName': json['fileName'],
    };
}

export function UploadPhotoItemRequestDtoToJSON(json: any): UploadPhotoItemRequestDto {
    return UploadPhotoItemRequestDtoToJSONTyped(json, false);
}

export function UploadPhotoItemRequestDtoToJSONTyped(value?: UploadPhotoItemRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': VehiclePhotoTypeToJSON(value['type']),
        'clientFileId': value['clientFileId'],
        'fileName': value['fileName'],
    };
}

