/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleDocumentType } from './VehicleDocumentType';
import {
    VehicleDocumentTypeFromJSON,
    VehicleDocumentTypeFromJSONTyped,
    VehicleDocumentTypeToJSON,
    VehicleDocumentTypeToJSONTyped,
} from './VehicleDocumentType';

/**
 * 
 * @export
 * @interface UploadDocumentItemRequestDto
 */
export interface UploadDocumentItemRequestDto {
    /**
     * 
     * @type {VehicleDocumentType}
     * @memberof UploadDocumentItemRequestDto
     */
    type: VehicleDocumentType;
    /**
     * 
     * @type {string}
     * @memberof UploadDocumentItemRequestDto
     */
    clientFileId: string;
    /**
     * 
     * @type {string}
     * @memberof UploadDocumentItemRequestDto
     */
    fileName: string;
}



/**
 * Check if a given object implements the UploadDocumentItemRequestDto interface.
 */
export function instanceOfUploadDocumentItemRequestDto(value: object): value is UploadDocumentItemRequestDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('clientFileId' in value) || value['clientFileId'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    return true;
}

export function UploadDocumentItemRequestDtoFromJSON(json: any): UploadDocumentItemRequestDto {
    return UploadDocumentItemRequestDtoFromJSONTyped(json, false);
}

export function UploadDocumentItemRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadDocumentItemRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': VehicleDocumentTypeFromJSON(json['type']),
        'clientFileId': json['clientFileId'],
        'fileName': json['fileName'],
    };
}

export function UploadDocumentItemRequestDtoToJSON(json: any): UploadDocumentItemRequestDto {
    return UploadDocumentItemRequestDtoToJSONTyped(json, false);
}

export function UploadDocumentItemRequestDtoToJSONTyped(value?: UploadDocumentItemRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': VehicleDocumentTypeToJSON(value['type']),
        'clientFileId': value['clientFileId'],
        'fileName': value['fileName'],
    };
}

