/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadPublicPhotoItemRequestDto
 */
export interface UploadPublicPhotoItemRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UploadPublicPhotoItemRequestDto
     */
    clientFileId: string;
    /**
     * 
     * @type {string}
     * @memberof UploadPublicPhotoItemRequestDto
     */
    fileName: string;
    /**
     * 
     * @type {number}
     * @memberof UploadPublicPhotoItemRequestDto
     */
    id: number;
}

/**
 * Check if a given object implements the UploadPublicPhotoItemRequestDto interface.
 */
export function instanceOfUploadPublicPhotoItemRequestDto(value: object): value is UploadPublicPhotoItemRequestDto {
    if (!('clientFileId' in value) || value['clientFileId'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UploadPublicPhotoItemRequestDtoFromJSON(json: any): UploadPublicPhotoItemRequestDto {
    return UploadPublicPhotoItemRequestDtoFromJSONTyped(json, false);
}

export function UploadPublicPhotoItemRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadPublicPhotoItemRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'clientFileId': json['clientFileId'],
        'fileName': json['fileName'],
        'id': json['id'],
    };
}

export function UploadPublicPhotoItemRequestDtoToJSON(json: any): UploadPublicPhotoItemRequestDto {
    return UploadPublicPhotoItemRequestDtoToJSONTyped(json, false);
}

export function UploadPublicPhotoItemRequestDtoToJSONTyped(value?: UploadPublicPhotoItemRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientFileId': value['clientFileId'],
        'fileName': value['fileName'],
        'id': value['id'],
    };
}

