/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserAddressResponseDto } from './UserAddressResponseDto';
import {
    UserAddressResponseDtoFromJSON,
    UserAddressResponseDtoFromJSONTyped,
    UserAddressResponseDtoToJSON,
    UserAddressResponseDtoToJSONTyped,
} from './UserAddressResponseDto';

/**
 * 
 * @export
 * @interface UserFinancialSettingsResponseDto
 */
export interface UserFinancialSettingsResponseDto {
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsResponseDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsResponseDto
     */
    surname: string;
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsResponseDto
     */
    ico: string;
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsResponseDto
     */
    dic: string;
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsResponseDto
     */
    companyName: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserFinancialSettingsResponseDto
     */
    isCompany: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsResponseDto
     */
    iban: string;
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsResponseDto
     */
    swift: string;
    /**
     * 
     * @type {UserAddressResponseDto}
     * @memberof UserFinancialSettingsResponseDto
     */
    address?: UserAddressResponseDto;
    /**
     * 
     * @type {UserAddressResponseDto}
     * @memberof UserFinancialSettingsResponseDto
     */
    mailingAddress?: UserAddressResponseDto;
}

/**
 * Check if a given object implements the UserFinancialSettingsResponseDto interface.
 */
export function instanceOfUserFinancialSettingsResponseDto(value: object): value is UserFinancialSettingsResponseDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('surname' in value) || value['surname'] === undefined) return false;
    if (!('ico' in value) || value['ico'] === undefined) return false;
    if (!('dic' in value) || value['dic'] === undefined) return false;
    if (!('companyName' in value) || value['companyName'] === undefined) return false;
    if (!('isCompany' in value) || value['isCompany'] === undefined) return false;
    if (!('iban' in value) || value['iban'] === undefined) return false;
    if (!('swift' in value) || value['swift'] === undefined) return false;
    return true;
}

export function UserFinancialSettingsResponseDtoFromJSON(json: any): UserFinancialSettingsResponseDto {
    return UserFinancialSettingsResponseDtoFromJSONTyped(json, false);
}

export function UserFinancialSettingsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFinancialSettingsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'surname': json['surname'],
        'ico': json['ico'],
        'dic': json['dic'],
        'companyName': json['companyName'],
        'isCompany': json['isCompany'],
        'iban': json['iban'],
        'swift': json['swift'],
        'address': json['address'] == null ? undefined : UserAddressResponseDtoFromJSON(json['address']),
        'mailingAddress': json['mailingAddress'] == null ? undefined : UserAddressResponseDtoFromJSON(json['mailingAddress']),
    };
}

export function UserFinancialSettingsResponseDtoToJSON(json: any): UserFinancialSettingsResponseDto {
    return UserFinancialSettingsResponseDtoToJSONTyped(json, false);
}

export function UserFinancialSettingsResponseDtoToJSONTyped(value?: UserFinancialSettingsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'surname': value['surname'],
        'ico': value['ico'],
        'dic': value['dic'],
        'companyName': value['companyName'],
        'isCompany': value['isCompany'],
        'iban': value['iban'],
        'swift': value['swift'],
        'address': UserAddressResponseDtoToJSON(value['address']),
        'mailingAddress': UserAddressResponseDtoToJSON(value['mailingAddress']),
    };
}

