/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDetailResponseDto
 */
export interface UserDetailResponseDto {
    /**
     * 
     * @type {number}
     * @memberof UserDetailResponseDto
     */
    id: number;
}

/**
 * Check if a given object implements the UserDetailResponseDto interface.
 */
export function instanceOfUserDetailResponseDto(value: object): value is UserDetailResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UserDetailResponseDtoFromJSON(json: any): UserDetailResponseDto {
    return UserDetailResponseDtoFromJSONTyped(json, false);
}

export function UserDetailResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetailResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function UserDetailResponseDtoToJSON(json: any): UserDetailResponseDto {
    return UserDetailResponseDtoToJSONTyped(json, false);
}

export function UserDetailResponseDtoToJSONTyped(value?: UserDetailResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

