/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserFinancialSettingsRequestDto } from './UserFinancialSettingsRequestDto';
import {
    UserFinancialSettingsRequestDtoFromJSON,
    UserFinancialSettingsRequestDtoFromJSONTyped,
    UserFinancialSettingsRequestDtoToJSON,
    UserFinancialSettingsRequestDtoToJSONTyped,
} from './UserFinancialSettingsRequestDto';
import type { NotificationSettingsRequestDto } from './NotificationSettingsRequestDto';
import {
    NotificationSettingsRequestDtoFromJSON,
    NotificationSettingsRequestDtoFromJSONTyped,
    NotificationSettingsRequestDtoToJSON,
    NotificationSettingsRequestDtoToJSONTyped,
} from './NotificationSettingsRequestDto';
import type { Locales } from './Locales';
import {
    LocalesFromJSON,
    LocalesFromJSONTyped,
    LocalesToJSON,
    LocalesToJSONTyped,
} from './Locales';

/**
 * 
 * @export
 * @interface UserSettingsRequestDto
 */
export interface UserSettingsRequestDto {
    /**
     * 
     * @type {UserFinancialSettingsRequestDto}
     * @memberof UserSettingsRequestDto
     */
    userFinancialSettings: UserFinancialSettingsRequestDto;
    /**
     * 
     * @type {string}
     * @memberof UserSettingsRequestDto
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {Locales}
     * @memberof UserSettingsRequestDto
     */
    locale?: Locales;
    /**
     * 
     * @type {Array<NotificationSettingsRequestDto>}
     * @memberof UserSettingsRequestDto
     */
    notifications?: Array<NotificationSettingsRequestDto> | null;
}



/**
 * Check if a given object implements the UserSettingsRequestDto interface.
 */
export function instanceOfUserSettingsRequestDto(value: object): value is UserSettingsRequestDto {
    if (!('userFinancialSettings' in value) || value['userFinancialSettings'] === undefined) return false;
    return true;
}

export function UserSettingsRequestDtoFromJSON(json: any): UserSettingsRequestDto {
    return UserSettingsRequestDtoFromJSONTyped(json, false);
}

export function UserSettingsRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSettingsRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userFinancialSettings': UserFinancialSettingsRequestDtoFromJSON(json['userFinancialSettings']),
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'locale': json['locale'] == null ? undefined : LocalesFromJSON(json['locale']),
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationSettingsRequestDtoFromJSON)),
    };
}

export function UserSettingsRequestDtoToJSON(json: any): UserSettingsRequestDto {
    return UserSettingsRequestDtoToJSONTyped(json, false);
}

export function UserSettingsRequestDtoToJSONTyped(value?: UserSettingsRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userFinancialSettings': UserFinancialSettingsRequestDtoToJSON(value['userFinancialSettings']),
        'phoneNumber': value['phoneNumber'],
        'locale': LocalesToJSON(value['locale']),
        'notifications': value['notifications'] == null ? undefined : ((value['notifications'] as Array<any>).map(NotificationSettingsRequestDtoToJSON)),
    };
}

