/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserFinancialSettingsResponseDto } from './UserFinancialSettingsResponseDto';
import {
    UserFinancialSettingsResponseDtoFromJSON,
    UserFinancialSettingsResponseDtoFromJSONTyped,
    UserFinancialSettingsResponseDtoToJSON,
    UserFinancialSettingsResponseDtoToJSONTyped,
} from './UserFinancialSettingsResponseDto';
import type { NotificationsEnum } from './NotificationsEnum';
import {
    NotificationsEnumFromJSON,
    NotificationsEnumFromJSONTyped,
    NotificationsEnumToJSON,
    NotificationsEnumToJSONTyped,
} from './NotificationsEnum';

/**
 * 
 * @export
 * @interface UserSettingsResponseDto
 */
export interface UserSettingsResponseDto {
    /**
     * 
     * @type {string}
     * @memberof UserSettingsResponseDto
     */
    phoneNumber: string;
    /**
     * 
     * @type {Array<NotificationsEnum>}
     * @memberof UserSettingsResponseDto
     */
    notifications: Array<NotificationsEnum>;
    /**
     * 
     * @type {UserFinancialSettingsResponseDto}
     * @memberof UserSettingsResponseDto
     */
    financialSettings?: UserFinancialSettingsResponseDto;
    /**
     * 
     * @type {number}
     * @memberof UserSettingsResponseDto
     */
    transportRequirementsId?: number | null;
}

/**
 * Check if a given object implements the UserSettingsResponseDto interface.
 */
export function instanceOfUserSettingsResponseDto(value: object): value is UserSettingsResponseDto {
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('notifications' in value) || value['notifications'] === undefined) return false;
    return true;
}

export function UserSettingsResponseDtoFromJSON(json: any): UserSettingsResponseDto {
    return UserSettingsResponseDtoFromJSONTyped(json, false);
}

export function UserSettingsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSettingsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneNumber': json['phoneNumber'],
        'notifications': ((json['notifications'] as Array<any>).map(NotificationsEnumFromJSON)),
        'financialSettings': json['financialSettings'] == null ? undefined : UserFinancialSettingsResponseDtoFromJSON(json['financialSettings']),
        'transportRequirementsId': json['transportRequirementsId'] == null ? undefined : json['transportRequirementsId'],
    };
}

export function UserSettingsResponseDtoToJSON(json: any): UserSettingsResponseDto {
    return UserSettingsResponseDtoToJSONTyped(json, false);
}

export function UserSettingsResponseDtoToJSONTyped(value?: UserSettingsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phoneNumber': value['phoneNumber'],
        'notifications': ((value['notifications'] as Array<any>).map(NotificationsEnumToJSON)),
        'financialSettings': UserFinancialSettingsResponseDtoToJSON(value['financialSettings']),
        'transportRequirementsId': value['transportRequirementsId'],
    };
}

