/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Country } from './Country';
import {
    CountryFromJSON,
    CountryFromJSONTyped,
    CountryToJSON,
    CountryToJSONTyped,
} from './Country';

/**
 * 
 * @export
 * @interface UserAddressRequestDto
 */
export interface UserAddressRequestDto {
    /**
     * 
     * @type {Country}
     * @memberof UserAddressRequestDto
     */
    country?: Country;
    /**
     * 
     * @type {string}
     * @memberof UserAddressRequestDto
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAddressRequestDto
     */
    psc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAddressRequestDto
     */
    street?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAddressRequestDto
     */
    houseNumber?: string | null;
}



/**
 * Check if a given object implements the UserAddressRequestDto interface.
 */
export function instanceOfUserAddressRequestDto(value: object): value is UserAddressRequestDto {
    return true;
}

export function UserAddressRequestDtoFromJSON(json: any): UserAddressRequestDto {
    return UserAddressRequestDtoFromJSONTyped(json, false);
}

export function UserAddressRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAddressRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'] == null ? undefined : CountryFromJSON(json['country']),
        'city': json['city'] == null ? undefined : json['city'],
        'psc': json['psc'] == null ? undefined : json['psc'],
        'street': json['street'] == null ? undefined : json['street'],
        'houseNumber': json['houseNumber'] == null ? undefined : json['houseNumber'],
    };
}

export function UserAddressRequestDtoToJSON(json: any): UserAddressRequestDto {
    return UserAddressRequestDtoToJSONTyped(json, false);
}

export function UserAddressRequestDtoToJSONTyped(value?: UserAddressRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': CountryToJSON(value['country']),
        'city': value['city'],
        'psc': value['psc'],
        'street': value['street'],
        'houseNumber': value['houseNumber'],
    };
}

