/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserConfigResponseDto
 */
export interface UserConfigResponseDto {
    /**
     * 
     * @type {Date}
     * @memberof UserConfigResponseDto
     */
    created: Date;
    /**
     * 
     * @type {number}
     * @memberof UserConfigResponseDto
     */
    tripOfferCommissionPercentage: number;
}

/**
 * Check if a given object implements the UserConfigResponseDto interface.
 */
export function instanceOfUserConfigResponseDto(value: object): value is UserConfigResponseDto {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('tripOfferCommissionPercentage' in value) || value['tripOfferCommissionPercentage'] === undefined) return false;
    return true;
}

export function UserConfigResponseDtoFromJSON(json: any): UserConfigResponseDto {
    return UserConfigResponseDtoFromJSONTyped(json, false);
}

export function UserConfigResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserConfigResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'created': (new Date(json['created'])),
        'tripOfferCommissionPercentage': json['tripOfferCommissionPercentage'],
    };
}

export function UserConfigResponseDtoToJSON(json: any): UserConfigResponseDto {
    return UserConfigResponseDtoToJSONTyped(json, false);
}

export function UserConfigResponseDtoToJSONTyped(value?: UserConfigResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'].toISOString(),
        'tripOfferCommissionPercentage': value['tripOfferCommissionPercentage'],
    };
}

