/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserAddressRequestDto } from './UserAddressRequestDto';
import {
    UserAddressRequestDtoFromJSON,
    UserAddressRequestDtoFromJSONTyped,
    UserAddressRequestDtoToJSON,
    UserAddressRequestDtoToJSONTyped,
} from './UserAddressRequestDto';

/**
 * 
 * @export
 * @interface UserFinancialSettingsRequestDto
 */
export interface UserFinancialSettingsRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsRequestDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsRequestDto
     */
    surname: string;
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsRequestDto
     */
    ico: string;
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsRequestDto
     */
    dic: string;
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsRequestDto
     */
    companyName: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserFinancialSettingsRequestDto
     */
    isCompany: boolean;
    /**
     * 
     * @type {UserAddressRequestDto}
     * @memberof UserFinancialSettingsRequestDto
     */
    address: UserAddressRequestDto;
    /**
     * 
     * @type {UserAddressRequestDto}
     * @memberof UserFinancialSettingsRequestDto
     */
    mailingAddress: UserAddressRequestDto;
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsRequestDto
     */
    iban: string;
    /**
     * 
     * @type {string}
     * @memberof UserFinancialSettingsRequestDto
     */
    swift: string;
}

/**
 * Check if a given object implements the UserFinancialSettingsRequestDto interface.
 */
export function instanceOfUserFinancialSettingsRequestDto(value: object): value is UserFinancialSettingsRequestDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('surname' in value) || value['surname'] === undefined) return false;
    if (!('ico' in value) || value['ico'] === undefined) return false;
    if (!('dic' in value) || value['dic'] === undefined) return false;
    if (!('companyName' in value) || value['companyName'] === undefined) return false;
    if (!('isCompany' in value) || value['isCompany'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('mailingAddress' in value) || value['mailingAddress'] === undefined) return false;
    if (!('iban' in value) || value['iban'] === undefined) return false;
    if (!('swift' in value) || value['swift'] === undefined) return false;
    return true;
}

export function UserFinancialSettingsRequestDtoFromJSON(json: any): UserFinancialSettingsRequestDto {
    return UserFinancialSettingsRequestDtoFromJSONTyped(json, false);
}

export function UserFinancialSettingsRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFinancialSettingsRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'surname': json['surname'],
        'ico': json['ico'],
        'dic': json['dic'],
        'companyName': json['companyName'],
        'isCompany': json['isCompany'],
        'address': UserAddressRequestDtoFromJSON(json['address']),
        'mailingAddress': UserAddressRequestDtoFromJSON(json['mailingAddress']),
        'iban': json['iban'],
        'swift': json['swift'],
    };
}

export function UserFinancialSettingsRequestDtoToJSON(json: any): UserFinancialSettingsRequestDto {
    return UserFinancialSettingsRequestDtoToJSONTyped(json, false);
}

export function UserFinancialSettingsRequestDtoToJSONTyped(value?: UserFinancialSettingsRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'surname': value['surname'],
        'ico': value['ico'],
        'dic': value['dic'],
        'companyName': value['companyName'],
        'isCompany': value['isCompany'],
        'address': UserAddressRequestDtoToJSON(value['address']),
        'mailingAddress': UserAddressRequestDtoToJSON(value['mailingAddress']),
        'iban': value['iban'],
        'swift': value['swift'],
    };
}

