/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EuroStandard } from './EuroStandard';
import {
    EuroStandardFromJSON,
    EuroStandardFromJSONTyped,
    EuroStandardToJSON,
    EuroStandardToJSONTyped,
} from './EuroStandard';
import type { FileResponseDto } from './FileResponseDto';
import {
    FileResponseDtoFromJSON,
    FileResponseDtoFromJSONTyped,
    FileResponseDtoToJSON,
    FileResponseDtoToJSONTyped,
} from './FileResponseDto';
import type { PlaceResponseDto } from './PlaceResponseDto';
import {
    PlaceResponseDtoFromJSON,
    PlaceResponseDtoFromJSONTyped,
    PlaceResponseDtoToJSON,
    PlaceResponseDtoToJSONTyped,
} from './PlaceResponseDto';
import type { VehicleStatus } from './VehicleStatus';
import {
    VehicleStatusFromJSON,
    VehicleStatusFromJSONTyped,
    VehicleStatusToJSON,
    VehicleStatusToJSONTyped,
} from './VehicleStatus';
import type { Amenities } from './Amenities';
import {
    AmenitiesFromJSON,
    AmenitiesFromJSONTyped,
    AmenitiesToJSON,
    AmenitiesToJSONTyped,
} from './Amenities';

/**
 * 
 * @export
 * @interface VehicleResponseDto
 */
export interface VehicleResponseDto {
    /**
     * 
     * @type {number}
     * @memberof VehicleResponseDto
     */
    id: number;
    /**
     * 
     * @type {VehicleStatus}
     * @memberof VehicleResponseDto
     */
    status: VehicleStatus;
    /**
     * 
     * @type {string}
     * @memberof VehicleResponseDto
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof VehicleResponseDto
     */
    isVerifiedForTransporting: boolean;
    /**
     * 
     * @type {string}
     * @memberof VehicleResponseDto
     */
    registrationSign: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleResponseDto
     */
    vin: string;
    /**
     * 
     * @type {Date}
     * @memberof VehicleResponseDto
     */
    stkExpired: Date;
    /**
     * 
     * @type {number}
     * @memberof VehicleResponseDto
     */
    yearOfManufacture: number;
    /**
     * 
     * @type {number}
     * @memberof VehicleResponseDto
     */
    personsCapacity: number;
    /**
     * 
     * @type {EuroStandard}
     * @memberof VehicleResponseDto
     */
    euro: EuroStandard;
    /**
     * 
     * @type {Array<Amenities>}
     * @memberof VehicleResponseDto
     */
    amenities: Array<Amenities>;
    /**
     * 
     * @type {number}
     * @memberof VehicleResponseDto
     */
    handicappedUserCount: number;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof VehicleResponseDto
     */
    frontPhoto?: FileResponseDto;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof VehicleResponseDto
     */
    rearPhoto?: FileResponseDto;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof VehicleResponseDto
     */
    leftSidePhoto?: FileResponseDto;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof VehicleResponseDto
     */
    rightSidePhoto?: FileResponseDto;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof VehicleResponseDto
     */
    interierPhoto1?: FileResponseDto;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof VehicleResponseDto
     */
    interierPhoto2?: FileResponseDto;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof VehicleResponseDto
     */
    technicalCertificate1?: FileResponseDto;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof VehicleResponseDto
     */
    technicalCertificate2?: FileResponseDto;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof VehicleResponseDto
     */
    insurance?: FileResponseDto;
    /**
     * 
     * @type {PlaceResponseDto}
     * @memberof VehicleResponseDto
     */
    departureStation?: PlaceResponseDto;
}



/**
 * Check if a given object implements the VehicleResponseDto interface.
 */
export function instanceOfVehicleResponseDto(value: object): value is VehicleResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('isVerifiedForTransporting' in value) || value['isVerifiedForTransporting'] === undefined) return false;
    if (!('registrationSign' in value) || value['registrationSign'] === undefined) return false;
    if (!('vin' in value) || value['vin'] === undefined) return false;
    if (!('stkExpired' in value) || value['stkExpired'] === undefined) return false;
    if (!('yearOfManufacture' in value) || value['yearOfManufacture'] === undefined) return false;
    if (!('personsCapacity' in value) || value['personsCapacity'] === undefined) return false;
    if (!('euro' in value) || value['euro'] === undefined) return false;
    if (!('amenities' in value) || value['amenities'] === undefined) return false;
    if (!('handicappedUserCount' in value) || value['handicappedUserCount'] === undefined) return false;
    return true;
}

export function VehicleResponseDtoFromJSON(json: any): VehicleResponseDto {
    return VehicleResponseDtoFromJSONTyped(json, false);
}

export function VehicleResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': VehicleStatusFromJSON(json['status']),
        'name': json['name'],
        'isVerifiedForTransporting': json['isVerifiedForTransporting'],
        'registrationSign': json['registrationSign'],
        'vin': json['vin'],
        'stkExpired': (new Date(json['stkExpired'])),
        'yearOfManufacture': json['yearOfManufacture'],
        'personsCapacity': json['personsCapacity'],
        'euro': EuroStandardFromJSON(json['euro']),
        'amenities': ((json['amenities'] as Array<any>).map(AmenitiesFromJSON)),
        'handicappedUserCount': json['handicappedUserCount'],
        'frontPhoto': json['frontPhoto'] == null ? undefined : FileResponseDtoFromJSON(json['frontPhoto']),
        'rearPhoto': json['rearPhoto'] == null ? undefined : FileResponseDtoFromJSON(json['rearPhoto']),
        'leftSidePhoto': json['leftSidePhoto'] == null ? undefined : FileResponseDtoFromJSON(json['leftSidePhoto']),
        'rightSidePhoto': json['rightSidePhoto'] == null ? undefined : FileResponseDtoFromJSON(json['rightSidePhoto']),
        'interierPhoto1': json['interierPhoto1'] == null ? undefined : FileResponseDtoFromJSON(json['interierPhoto1']),
        'interierPhoto2': json['interierPhoto2'] == null ? undefined : FileResponseDtoFromJSON(json['interierPhoto2']),
        'technicalCertificate1': json['technicalCertificate1'] == null ? undefined : FileResponseDtoFromJSON(json['technicalCertificate1']),
        'technicalCertificate2': json['technicalCertificate2'] == null ? undefined : FileResponseDtoFromJSON(json['technicalCertificate2']),
        'insurance': json['insurance'] == null ? undefined : FileResponseDtoFromJSON(json['insurance']),
        'departureStation': json['departureStation'] == null ? undefined : PlaceResponseDtoFromJSON(json['departureStation']),
    };
}

export function VehicleResponseDtoToJSON(json: any): VehicleResponseDto {
    return VehicleResponseDtoToJSONTyped(json, false);
}

export function VehicleResponseDtoToJSONTyped(value?: VehicleResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': VehicleStatusToJSON(value['status']),
        'name': value['name'],
        'isVerifiedForTransporting': value['isVerifiedForTransporting'],
        'registrationSign': value['registrationSign'],
        'vin': value['vin'],
        'stkExpired': ((value['stkExpired']).toISOString()),
        'yearOfManufacture': value['yearOfManufacture'],
        'personsCapacity': value['personsCapacity'],
        'euro': EuroStandardToJSON(value['euro']),
        'amenities': ((value['amenities'] as Array<any>).map(AmenitiesToJSON)),
        'handicappedUserCount': value['handicappedUserCount'],
        'frontPhoto': FileResponseDtoToJSON(value['frontPhoto']),
        'rearPhoto': FileResponseDtoToJSON(value['rearPhoto']),
        'leftSidePhoto': FileResponseDtoToJSON(value['leftSidePhoto']),
        'rightSidePhoto': FileResponseDtoToJSON(value['rightSidePhoto']),
        'interierPhoto1': FileResponseDtoToJSON(value['interierPhoto1']),
        'interierPhoto2': FileResponseDtoToJSON(value['interierPhoto2']),
        'technicalCertificate1': FileResponseDtoToJSON(value['technicalCertificate1']),
        'technicalCertificate2': FileResponseDtoToJSON(value['technicalCertificate2']),
        'insurance': FileResponseDtoToJSON(value['insurance']),
        'departureStation': PlaceResponseDtoToJSON(value['departureStation']),
    };
}

