/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VehicleStatus = {
    DRAFT: 'Draft',
    PENDING_VERIFICATION: 'PendingVerification',
    VERIFIED: 'Verified',
    ARCHIVED: 'Archived',
    NOT_VERIFIED: 'NotVerified'
} as const;
export type VehicleStatus = typeof VehicleStatus[keyof typeof VehicleStatus];


export function instanceOfVehicleStatus(value: any): boolean {
    for (const key in VehicleStatus) {
        if (Object.prototype.hasOwnProperty.call(VehicleStatus, key)) {
            if (VehicleStatus[key as keyof typeof VehicleStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VehicleStatusFromJSON(json: any): VehicleStatus {
    return VehicleStatusFromJSONTyped(json, false);
}

export function VehicleStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleStatus {
    return json as VehicleStatus;
}

export function VehicleStatusToJSON(value?: VehicleStatus | null): any {
    return value as any;
}

export function VehicleStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): VehicleStatus {
    return value as VehicleStatus;
}

