/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehiclePhotoType } from './VehiclePhotoType';
import {
    VehiclePhotoTypeFromJSON,
    VehiclePhotoTypeFromJSONTyped,
    VehiclePhotoTypeToJSON,
    VehiclePhotoTypeToJSONTyped,
} from './VehiclePhotoType';
import type { FileResponseDto } from './FileResponseDto';
import {
    FileResponseDtoFromJSON,
    FileResponseDtoFromJSONTyped,
    FileResponseDtoToJSON,
    FileResponseDtoToJSONTyped,
} from './FileResponseDto';

/**
 * 
 * @export
 * @interface VehiclePhotoResponseDto
 */
export interface VehiclePhotoResponseDto {
    /**
     * 
     * @type {number}
     * @memberof VehiclePhotoResponseDto
     */
    id: number;
    /**
     * 
     * @type {VehiclePhotoType}
     * @memberof VehiclePhotoResponseDto
     */
    type: VehiclePhotoType;
    /**
     * 
     * @type {boolean}
     * @memberof VehiclePhotoResponseDto
     */
    isPublic: boolean;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof VehiclePhotoResponseDto
     */
    file?: FileResponseDto;
}



/**
 * Check if a given object implements the VehiclePhotoResponseDto interface.
 */
export function instanceOfVehiclePhotoResponseDto(value: object): value is VehiclePhotoResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
    return true;
}

export function VehiclePhotoResponseDtoFromJSON(json: any): VehiclePhotoResponseDto {
    return VehiclePhotoResponseDtoFromJSONTyped(json, false);
}

export function VehiclePhotoResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehiclePhotoResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': VehiclePhotoTypeFromJSON(json['type']),
        'isPublic': json['isPublic'],
        'file': json['file'] == null ? undefined : FileResponseDtoFromJSON(json['file']),
    };
}

export function VehiclePhotoResponseDtoToJSON(json: any): VehiclePhotoResponseDto {
    return VehiclePhotoResponseDtoToJSONTyped(json, false);
}

export function VehiclePhotoResponseDtoToJSONTyped(value?: VehiclePhotoResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': VehiclePhotoTypeToJSON(value['type']),
        'isPublic': value['isPublic'],
        'file': FileResponseDtoToJSON(value['file']),
    };
}

