/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehiclePhotoType } from './VehiclePhotoType';
import {
    VehiclePhotoTypeFromJSON,
    VehiclePhotoTypeFromJSONTyped,
    VehiclePhotoTypeToJSON,
    VehiclePhotoTypeToJSONTyped,
} from './VehiclePhotoType';

/**
 * 
 * @export
 * @interface VehiclePhotoItemRequestDto
 */
export interface VehiclePhotoItemRequestDto {
    /**
     * 
     * @type {VehiclePhotoType}
     * @memberof VehiclePhotoItemRequestDto
     */
    type: VehiclePhotoType;
}



/**
 * Check if a given object implements the VehiclePhotoItemRequestDto interface.
 */
export function instanceOfVehiclePhotoItemRequestDto(value: object): value is VehiclePhotoItemRequestDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function VehiclePhotoItemRequestDtoFromJSON(json: any): VehiclePhotoItemRequestDto {
    return VehiclePhotoItemRequestDtoFromJSONTyped(json, false);
}

export function VehiclePhotoItemRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehiclePhotoItemRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': VehiclePhotoTypeFromJSON(json['type']),
    };
}

export function VehiclePhotoItemRequestDtoToJSON(json: any): VehiclePhotoItemRequestDto {
    return VehiclePhotoItemRequestDtoToJSONTyped(json, false);
}

export function VehiclePhotoItemRequestDtoToJSONTyped(value?: VehiclePhotoItemRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': VehiclePhotoTypeToJSON(value['type']),
    };
}

