/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadSasUrlResponseDto } from './UploadSasUrlResponseDto';
import {
    UploadSasUrlResponseDtoFromJSON,
    UploadSasUrlResponseDtoFromJSONTyped,
    UploadSasUrlResponseDtoToJSON,
    UploadSasUrlResponseDtoToJSONTyped,
} from './UploadSasUrlResponseDto';

/**
 * 
 * @export
 * @interface VehicleUploadSasUrlResponseDto
 */
export interface VehicleUploadSasUrlResponseDto {
    /**
     * 
     * @type {Array<UploadSasUrlResponseDto>}
     * @memberof VehicleUploadSasUrlResponseDto
     */
    photos: Array<UploadSasUrlResponseDto>;
    /**
     * 
     * @type {Array<UploadSasUrlResponseDto>}
     * @memberof VehicleUploadSasUrlResponseDto
     */
    documents: Array<UploadSasUrlResponseDto>;
}

/**
 * Check if a given object implements the VehicleUploadSasUrlResponseDto interface.
 */
export function instanceOfVehicleUploadSasUrlResponseDto(value: object): value is VehicleUploadSasUrlResponseDto {
    if (!('photos' in value) || value['photos'] === undefined) return false;
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function VehicleUploadSasUrlResponseDtoFromJSON(json: any): VehicleUploadSasUrlResponseDto {
    return VehicleUploadSasUrlResponseDtoFromJSONTyped(json, false);
}

export function VehicleUploadSasUrlResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleUploadSasUrlResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'photos': ((json['photos'] as Array<any>).map(UploadSasUrlResponseDtoFromJSON)),
        'documents': ((json['documents'] as Array<any>).map(UploadSasUrlResponseDtoFromJSON)),
    };
}

export function VehicleUploadSasUrlResponseDtoToJSON(json: any): VehicleUploadSasUrlResponseDto {
    return VehicleUploadSasUrlResponseDtoToJSONTyped(json, false);
}

export function VehicleUploadSasUrlResponseDtoToJSONTyped(value?: VehicleUploadSasUrlResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'photos': ((value['photos'] as Array<any>).map(UploadSasUrlResponseDtoToJSON)),
        'documents': ((value['documents'] as Array<any>).map(UploadSasUrlResponseDtoToJSON)),
    };
}

