/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EuroStandard } from './EuroStandard';
import {
    EuroStandardFromJSON,
    EuroStandardFromJSONTyped,
    EuroStandardToJSON,
    EuroStandardToJSONTyped,
} from './EuroStandard';
import type { PlaceRequestDto } from './PlaceRequestDto';
import {
    PlaceRequestDtoFromJSON,
    PlaceRequestDtoFromJSONTyped,
    PlaceRequestDtoToJSON,
    PlaceRequestDtoToJSONTyped,
} from './PlaceRequestDto';
import type { Amenities } from './Amenities';
import {
    AmenitiesFromJSON,
    AmenitiesFromJSONTyped,
    AmenitiesToJSON,
    AmenitiesToJSONTyped,
} from './Amenities';

/**
 * 
 * @export
 * @interface VehicleRequestDto
 */
export interface VehicleRequestDto {
    /**
     * 
     * @type {string}
     * @memberof VehicleRequestDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VehicleRequestDto
     */
    registrationSign?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VehicleRequestDto
     */
    vin?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof VehicleRequestDto
     */
    stkExpired?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof VehicleRequestDto
     */
    yearOfManufacture?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VehicleRequestDto
     */
    personsCapacity?: number | null;
    /**
     * 
     * @type {EuroStandard}
     * @memberof VehicleRequestDto
     */
    euro?: EuroStandard;
    /**
     * 
     * @type {Array<Amenities>}
     * @memberof VehicleRequestDto
     */
    amenities?: Array<Amenities> | null;
    /**
     * 
     * @type {number}
     * @memberof VehicleRequestDto
     */
    handicappedUserCount?: number | null;
    /**
     * 
     * @type {PlaceRequestDto}
     * @memberof VehicleRequestDto
     */
    departureStation?: PlaceRequestDto;
}



/**
 * Check if a given object implements the VehicleRequestDto interface.
 */
export function instanceOfVehicleRequestDto(value: object): value is VehicleRequestDto {
    return true;
}

export function VehicleRequestDtoFromJSON(json: any): VehicleRequestDto {
    return VehicleRequestDtoFromJSONTyped(json, false);
}

export function VehicleRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'registrationSign': json['registrationSign'] == null ? undefined : json['registrationSign'],
        'vin': json['vin'] == null ? undefined : json['vin'],
        'stkExpired': json['stkExpired'] == null ? undefined : (new Date(json['stkExpired'])),
        'yearOfManufacture': json['yearOfManufacture'] == null ? undefined : json['yearOfManufacture'],
        'personsCapacity': json['personsCapacity'] == null ? undefined : json['personsCapacity'],
        'euro': json['euro'] == null ? undefined : EuroStandardFromJSON(json['euro']),
        'amenities': json['amenities'] == null ? undefined : ((json['amenities'] as Array<any>).map(AmenitiesFromJSON)),
        'handicappedUserCount': json['handicappedUserCount'] == null ? undefined : json['handicappedUserCount'],
        'departureStation': json['departureStation'] == null ? undefined : PlaceRequestDtoFromJSON(json['departureStation']),
    };
}

export function VehicleRequestDtoToJSON(json: any): VehicleRequestDto {
    return VehicleRequestDtoToJSONTyped(json, false);
}

export function VehicleRequestDtoToJSONTyped(value?: VehicleRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'registrationSign': value['registrationSign'],
        'vin': value['vin'],
        'stkExpired': value['stkExpired'] == null ? value['stkExpired'] : value['stkExpired'].toISOString(),
        'yearOfManufacture': value['yearOfManufacture'],
        'personsCapacity': value['personsCapacity'],
        'euro': EuroStandardToJSON(value['euro']),
        'amenities': value['amenities'] == null ? undefined : ((value['amenities'] as Array<any>).map(AmenitiesToJSON)),
        'handicappedUserCount': value['handicappedUserCount'],
        'departureStation': PlaceRequestDtoToJSON(value['departureStation']),
    };
}

