/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadDocumentItemRequestDto } from './UploadDocumentItemRequestDto';
import {
    UploadDocumentItemRequestDtoFromJSON,
    UploadDocumentItemRequestDtoFromJSONTyped,
    UploadDocumentItemRequestDtoToJSON,
    UploadDocumentItemRequestDtoToJSONTyped,
} from './UploadDocumentItemRequestDto';
import type { UploadPhotoItemRequestDto } from './UploadPhotoItemRequestDto';
import {
    UploadPhotoItemRequestDtoFromJSON,
    UploadPhotoItemRequestDtoFromJSONTyped,
    UploadPhotoItemRequestDtoToJSON,
    UploadPhotoItemRequestDtoToJSONTyped,
} from './UploadPhotoItemRequestDto';

/**
 * 
 * @export
 * @interface VehicleCreateUploadUrlFilesRequestDto
 */
export interface VehicleCreateUploadUrlFilesRequestDto {
    /**
     * 
     * @type {number}
     * @memberof VehicleCreateUploadUrlFilesRequestDto
     */
    vehicleId: number;
    /**
     * 
     * @type {Array<UploadPhotoItemRequestDto>}
     * @memberof VehicleCreateUploadUrlFilesRequestDto
     */
    photos: Array<UploadPhotoItemRequestDto>;
    /**
     * 
     * @type {Array<UploadDocumentItemRequestDto>}
     * @memberof VehicleCreateUploadUrlFilesRequestDto
     */
    documents: Array<UploadDocumentItemRequestDto>;
}

/**
 * Check if a given object implements the VehicleCreateUploadUrlFilesRequestDto interface.
 */
export function instanceOfVehicleCreateUploadUrlFilesRequestDto(value: object): value is VehicleCreateUploadUrlFilesRequestDto {
    if (!('vehicleId' in value) || value['vehicleId'] === undefined) return false;
    if (!('photos' in value) || value['photos'] === undefined) return false;
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function VehicleCreateUploadUrlFilesRequestDtoFromJSON(json: any): VehicleCreateUploadUrlFilesRequestDto {
    return VehicleCreateUploadUrlFilesRequestDtoFromJSONTyped(json, false);
}

export function VehicleCreateUploadUrlFilesRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleCreateUploadUrlFilesRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'vehicleId': json['vehicleId'],
        'photos': ((json['photos'] as Array<any>).map(UploadPhotoItemRequestDtoFromJSON)),
        'documents': ((json['documents'] as Array<any>).map(UploadDocumentItemRequestDtoFromJSON)),
    };
}

export function VehicleCreateUploadUrlFilesRequestDtoToJSON(json: any): VehicleCreateUploadUrlFilesRequestDto {
    return VehicleCreateUploadUrlFilesRequestDtoToJSONTyped(json, false);
}

export function VehicleCreateUploadUrlFilesRequestDtoToJSONTyped(value?: VehicleCreateUploadUrlFilesRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vehicleId': value['vehicleId'],
        'photos': ((value['photos'] as Array<any>).map(UploadPhotoItemRequestDtoToJSON)),
        'documents': ((value['documents'] as Array<any>).map(UploadDocumentItemRequestDtoToJSON)),
    };
}

