/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleDocumentType } from './VehicleDocumentType';
import {
    VehicleDocumentTypeFromJSON,
    VehicleDocumentTypeFromJSONTyped,
    VehicleDocumentTypeToJSON,
    VehicleDocumentTypeToJSONTyped,
} from './VehicleDocumentType';
import type { FileResponseDto } from './FileResponseDto';
import {
    FileResponseDtoFromJSON,
    FileResponseDtoFromJSONTyped,
    FileResponseDtoToJSON,
    FileResponseDtoToJSONTyped,
} from './FileResponseDto';

/**
 * 
 * @export
 * @interface VehicleDocumentResponseDto
 */
export interface VehicleDocumentResponseDto {
    /**
     * 
     * @type {number}
     * @memberof VehicleDocumentResponseDto
     */
    id: number;
    /**
     * 
     * @type {VehicleDocumentType}
     * @memberof VehicleDocumentResponseDto
     */
    type: VehicleDocumentType;
    /**
     * 
     * @type {FileResponseDto}
     * @memberof VehicleDocumentResponseDto
     */
    file?: FileResponseDto;
}



/**
 * Check if a given object implements the VehicleDocumentResponseDto interface.
 */
export function instanceOfVehicleDocumentResponseDto(value: object): value is VehicleDocumentResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function VehicleDocumentResponseDtoFromJSON(json: any): VehicleDocumentResponseDto {
    return VehicleDocumentResponseDtoFromJSONTyped(json, false);
}

export function VehicleDocumentResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleDocumentResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': VehicleDocumentTypeFromJSON(json['type']),
        'file': json['file'] == null ? undefined : FileResponseDtoFromJSON(json['file']),
    };
}

export function VehicleDocumentResponseDtoToJSON(json: any): VehicleDocumentResponseDto {
    return VehicleDocumentResponseDtoToJSONTyped(json, false);
}

export function VehicleDocumentResponseDtoToJSONTyped(value?: VehicleDocumentResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': VehicleDocumentTypeToJSON(value['type']),
        'file': FileResponseDtoToJSON(value['file']),
    };
}

