/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VisibilityStatus = {
    PENDING: 'Pending',
    PUBLISHED: 'Published'
} as const;
export type VisibilityStatus = typeof VisibilityStatus[keyof typeof VisibilityStatus];


export function instanceOfVisibilityStatus(value: any): boolean {
    for (const key in VisibilityStatus) {
        if (Object.prototype.hasOwnProperty.call(VisibilityStatus, key)) {
            if (VisibilityStatus[key as keyof typeof VisibilityStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VisibilityStatusFromJSON(json: any): VisibilityStatus {
    return VisibilityStatusFromJSONTyped(json, false);
}

export function VisibilityStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisibilityStatus {
    return json as VisibilityStatus;
}

export function VisibilityStatusToJSON(value?: VisibilityStatus | null): any {
    return value as any;
}

export function VisibilityStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): VisibilityStatus {
    return value as VisibilityStatus;
}

