// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "page": {
    "sign": {
      "emailPlaceholder": "Zadej svůj e-mail",
      "passwordPlaceholder": "Heslo",
      "passwordConfirmPlaceholder": "Potvrzení hesla",
      "enterEmail": "Zadejte email",
      "enterPassword": "Zadejte heslo",
      "invalidEmail": "Nesprávný email",
      "shortPassword": "Heslo je příliš krátké",
      "invalidPasswordConfirm": "Hesla nejsou totožná",
      "registration": {
        "registrationButton": "Registrovat"
      },
      "forgotPassword": {
        "sendForgotPasswordButton": "Obnovit heslo",
        "textRequestSent": "Poždavek se zpracovává. Kontrolujte si svuj email."
      },
      "resetPassword": {
        "tokenInvalid": "Token není validní",
        "submit": "Uložit heslo"
      }
    },
    "userSettings": {
      "name": "Jméno",
      "surname": "Příjmení",
      "phoneNumber": "Telefoní číslo",
      "ico": "IČO",
      "dic": "DIČ",
      "save": "Uložit",
      "iban": "IBAN",
      "swift": "SWIFT",
      "concessionNumber": "Koncesialni cislo",
      "companyName": "Nazev firmy",
      "city": "Mesto",
      "psc": "PSč",
      "street": "Ulice",
      "houseNumber": "Cislo domu"
    }
  },
  "component":  {
    "button": "test in CZ",
    "placeName": {
      "loadingPlace": "Načítání",
      "fillPlace": "Zadej místo"
    },
    "trip": {
      "stopFromLabel": "Místo nástupu",
      "timeFromLabel": "Čas nastupu",
      "stopToLabel": "Místo výstupu",
      "computedTimeToLabel": "Předpokládaný čas výstupu",
      "timeFromPlaceHolder": "Čas a datum",
      "directionKm": "km",
      "directionHours":  "h",
      "directionMinutes": "m"
    },
    "header": {
      "logoutButton": "Odhlásit se",
      "loginButton": "Přihlásit se"
    }
  }
};
export default messages;