// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "page": {
    "sign": {
      "loginHeading": "Přihlášení",
      "registrationHeading": "Registrace",
      "forgetPasswordHeading": "Zapomenuté heslo",
      "resetPasswordHeading": "Resetovat heslo",
      "emailPlaceholder": "E-mail",
      "passwordPlaceholder": "Heslo",
      "passwordConfirmPlaceholder": "Potvrzení hesla",
      "login": "Přihlásit se",
      "registration": "Registrace",
      "registrationButton": "Registrovat se",
      "forgetPassword": "Zapomenuté heslo",
      "forgetPasswordButton": "Poslat nové heslo",
      "forgetPasswordSent": "Nové heslo bylo odesláno na zadanou e-mailovou adresu.",
      "resetPasswordButton": "Resetovat heslo",
      "resetPasswordSent": "Heslo bylo resetováno.",
      "activeAccountHeadingSuccess": "Účet aktivován!",
      "activeAccountHeadingError": "Chyba při aktivaci účtu",
      "activeAccountMessageSuccess": "Váš účet byl úspěšně aktivován. Nyní se můžete přihlásit.",
      "activeAccountMessageError": "Při aktivaci účtu došlo k neočekávané chybě. Zkuste to prosím později.",
      "activeAccountMessageInvalidCode": "Je vyžadován platný kód pro aktivaci účtu. Zkontrolujte prosím odkaz z vaší e-mailové schránky.",
      "loginAfterActivation": "Nyní se můžete přihlásit"
    },
    "userSettings": {
      "userSettingsHeading": "Nastavení uživatele",
      "name": "Jméno",
      "surname": "Příjmení",
      "phoneNumber": "Telefoní číslo",
      "ico": "IČO",
      "dic": "DIČ",
      "save": "Uložit",
      "iban": "IBAN",
      "swift": "SWIFT",
      "concessionNumber": "Koncesialni cislo",
      "companyName": "Nazev firmy",
      "country": "Země",
      "city": "Mesto",
      "psc": "PSč",
      "street": "Ulice",
      "houseNumber": "Cislo domu",
      "isCompany": "Jste firma?",
      "notificationsHeading": "Notifikace",
      "bankInfoHeading": "Bankovní spojení",
      "transportRequirementsHeading": "Požadavky na dopravce",
      "verifiedForTransporting": "Ověřený pro dopravu",
      "notVerifiedForTransporting": "Neověřený pro dopravu",
      "businessRiskInsurance": "Pojištění podnikatelských rizik",
      "concessionDocuments": "Koncesní listina",
      "saveButton": "Uložit"
    },
    "trip": {
      "handicappedUserCount": "Počet vozíčkářů",
      "endDemand": "Kdy končí nabídka",
      "numberOfPassengers": "Počet cestujících",
      "dietForTransporter": "Diety pro řidiče",
      "removeRoute": "Odstranit trasu",
      "addRoute": "Přidat trasu",
      "createDemand": "Vytvořit poptávku"
    }
  },
  "component":  {
    "button": "test in CZ",
    "placeName": {
      "loadingPlace": "Načítání",
      "fillPlace": "Zadej místo"
    },
    "trip": {
      "stopFromLabel": "Místo nástupu",
      "timeFromLabel": "Čas nastupu",
      "stopToLabel": "Místo výstupu",
      "computedTimeToLabel": "Předpokládaný čas výstupu",
      "timeFromPlaceHolder": "Čas a datum",
      "directionKm": "km",
      "directionHours":  "h",
      "directionMinutes": "m",
      "amenities": {
        "BIKE": "Kolo",
        "SKI": "Lyže",
        "COFFEE": "Káva",
        "WIFI": "Wi-Fi",
        "AIR_CONDITIONING": "Klimatizace",
        "BICYCLE_LIFT": "Zvedák pro bicykle",
        "SKI_BOX": "Box pro lyže",
        "BOAT_LIFT": "Zvedák pro lodě",
        "WC": "WC",
        "TV": "TV",
        "USB_SOCKETS": "USB připojky",
        "SOCKETS_V230": "Zásuvka V230",
        "ADJUSTABLE_SEATS": "Přizpůsobitelné sedadla",
        "SEAT_BELTS": "Bezpečnostní pásy"
      }
    },
    "header": {
      "logoutButton": "Odhlásit se",
      "loginButton": "Přihlásit se",
      "registrationButton": "Registrace"
    },
    "pageNames": {
      "home": "Domů",
      "createTrip": "Nová cesta",
      "tripList": "Cesty",
      "adminUsers": "Uživatelé",
      "adminTrips": "Admin Cesty",
      "userSettings": "Uživatelské nastavení",
      "vehicles" : "Vozidla",
      "appConfig": "Nastavení aplikace",
      "emailConfig": "Nastavení emailů"
    }
  },
  "common": {
    "transporter": "Přepravce",
    "demander": "Zadavatel"
  },
  "errors": {
    "schemaErrors": {
      "formStatusLabel": "Vyskytla se chyba",
      "unexpectedError": "Neočekovaná chyba",
      "invalidEmail": "Neplatný email",
      "invalidPassword": "Neplatné heslo",
      "passwordConfirm": "Hesla se neshodují"
    },
    "apiErrors": {
      "UNKNOWN": "Neočekovaná chyba",
      "BANNED": "Uživatel je zabanován",
      "UNSUPPORTED_ROLE": "Nepodporovaná role",
      "UNKNOWN_ROLE": "Neznámá role",
      "LOGIN_FAILED": "Přihlášení se nezdařilo",
      "USER_EXISTS": "Uživatel již existuje",
      "UNKNOWN_EMAIL": "Neplatný email",
      "UNKNOWN_USER": "Uživatel nenalezen",
      "WRONG_PASSWORD":  "Nesprávné heslo",
      "INVALID_PASSWORD_TOKEN": "Neplatný token hesla",
      "INACTIVE": "Uživatel je neaktivní"
    }
  }
};
export default messages;