import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Header} from "@/src/components/compositions/header/header";
import {AuthProvider} from "@/src/app/contexts/AuthContext";
import {AuthorizationService} from "@/src/services/AuthorizationService";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const user = await AuthorizationService.getUserJson();

      return (
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <AuthProvider initialUser={user}>
                <Header user={user} />
                {children}
            </AuthProvider>
          </body>
        </html>
      );
}
