const img1 = require("./db/1.jpg");
const img2 = require("./db/2.jpg");
const img3 = require("./db/3.jpg");
const img4 = require("./db/4.jpg");
const img5 = require("./db/5.jpg");
const img6 = require("./db/6.png");
const img7 = require("./db/7.jpg");
const img8 = require("./db/8.png");
const img9 = require("./db/9.jpg");
const img10 = require("./db/10.jpg");
const img11 = require("./db/11.jpg");
const img12 = require("./db/12.jpg");
const img13 = require("./db/13.jpg");
const img14 = require("./db/14.jpg");
const img15 = require("./db/15.jpg");
const img16 = require("./db/16.jpg");
const img17 = require("./db/17.jpg");
const img18 = require("./db/18.jpg");
const img19 = require("./db/19.jpg");
const img20 = require("./db/20.jpg");

export const photos = [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15, img16, img17, img18, img19, img20];
export const qrPhoto = require("./db/qr.jpg")