/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppBusinessConfigResponseDto,
  EmailConfigResponseDto,
  TripReviewDataResponseDto,
  UpdateAppBusinessConfigRequestDto,
  UpdateEmailConfig,
  UpdateTripReviewRequestDto,
  UpdateUserConfigRequestDto,
  UserConfigRequestDto,
  UserConfigResponseDto,
} from '../models/index';
import {
    AppBusinessConfigResponseDtoFromJSON,
    AppBusinessConfigResponseDtoToJSON,
    EmailConfigResponseDtoFromJSON,
    EmailConfigResponseDtoToJSON,
    TripReviewDataResponseDtoFromJSON,
    TripReviewDataResponseDtoToJSON,
    UpdateAppBusinessConfigRequestDtoFromJSON,
    UpdateAppBusinessConfigRequestDtoToJSON,
    UpdateEmailConfigFromJSON,
    UpdateEmailConfigToJSON,
    UpdateTripReviewRequestDtoFromJSON,
    UpdateTripReviewRequestDtoToJSON,
    UpdateUserConfigRequestDtoFromJSON,
    UpdateUserConfigRequestDtoToJSON,
    UserConfigRequestDtoFromJSON,
    UserConfigRequestDtoToJSON,
    UserConfigResponseDtoFromJSON,
    UserConfigResponseDtoToJSON,
} from '../models/index';

export interface ApiAdminAllReviewsGetRequest {
    limit: number;
    offset: number;
}

export interface ApiAdminAppConfigPostRequest {
    updateAppBusinessConfigRequestDto?: UpdateAppBusinessConfigRequestDto;
}

export interface ApiAdminEmailConfigPostRequest {
    updateEmailConfig?: UpdateEmailConfig;
}

export interface ApiAdminUpdateReviewPostRequest {
    updateTripReviewRequestDto?: UpdateTripReviewRequestDto;
}

export interface ApiAdminUserConfigGetRequest {
    userConfigRequestDto?: UserConfigRequestDto;
}

export interface ApiAdminUserConfigPostRequest {
    updateUserConfigRequestDto?: UpdateUserConfigRequestDto;
}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     */
    async apiAdminAllReviewsGetRaw(requestParameters: ApiAdminAllReviewsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TripReviewDataResponseDto>>> {
        if (requestParameters['limit'] == null) {
            throw new runtime.RequiredError(
                'limit',
                'Required parameter "limit" was null or undefined when calling apiAdminAllReviewsGet().'
            );
        }

        if (requestParameters['offset'] == null) {
            throw new runtime.RequiredError(
                'offset',
                'Required parameter "offset" was null or undefined when calling apiAdminAllReviewsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['Limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['Offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Admin/allReviews`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TripReviewDataResponseDtoFromJSON));
    }

    /**
     */
    async apiAdminAllReviewsGet(requestParameters: ApiAdminAllReviewsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TripReviewDataResponseDto>> {
        const response = await this.apiAdminAllReviewsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAdminAppConfigGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppBusinessConfigResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Admin/appConfig`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppBusinessConfigResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiAdminAppConfigGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppBusinessConfigResponseDto> {
        const response = await this.apiAdminAppConfigGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAdminAppConfigPostRaw(requestParameters: ApiAdminAppConfigPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Admin/appConfig`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAppBusinessConfigRequestDtoToJSON(requestParameters['updateAppBusinessConfigRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAdminAppConfigPost(requestParameters: ApiAdminAppConfigPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAdminAppConfigPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAdminEmailConfigGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailConfigResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Admin/emailConfig`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailConfigResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiAdminEmailConfigGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailConfigResponseDto> {
        const response = await this.apiAdminEmailConfigGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAdminEmailConfigPostRaw(requestParameters: ApiAdminEmailConfigPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Admin/emailConfig`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEmailConfigToJSON(requestParameters['updateEmailConfig']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAdminEmailConfigPost(requestParameters: ApiAdminEmailConfigPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAdminEmailConfigPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAdminUpdateReviewPostRaw(requestParameters: ApiAdminUpdateReviewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Admin/updateReview`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTripReviewRequestDtoToJSON(requestParameters['updateTripReviewRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAdminUpdateReviewPost(requestParameters: ApiAdminUpdateReviewPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAdminUpdateReviewPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAdminUserConfigGetRaw(requestParameters: ApiAdminUserConfigGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserConfigResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Admin/userConfig`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: UserConfigRequestDtoToJSON(requestParameters['userConfigRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserConfigResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiAdminUserConfigGet(requestParameters: ApiAdminUserConfigGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserConfigResponseDto> {
        const response = await this.apiAdminUserConfigGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAdminUserConfigPostRaw(requestParameters: ApiAdminUserConfigPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Admin/userConfig`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserConfigRequestDtoToJSON(requestParameters['updateUserConfigRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAdminUserConfigPost(requestParameters: ApiAdminUserConfigPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAdminUserConfigPostRaw(requestParameters, initOverrides);
    }

}
