/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChangePasswordRequestDto,
  CheckTokenResponseDto,
  ErrorResponseDto,
  ForgetPasswordRequestDto,
  LoginRequestDto,
  LoginResponseDto,
} from '../models/index';
import {
    ChangePasswordRequestDtoFromJSON,
    ChangePasswordRequestDtoToJSON,
    CheckTokenResponseDtoFromJSON,
    CheckTokenResponseDtoToJSON,
    ErrorResponseDtoFromJSON,
    ErrorResponseDtoToJSON,
    ForgetPasswordRequestDtoFromJSON,
    ForgetPasswordRequestDtoToJSON,
    LoginRequestDtoFromJSON,
    LoginRequestDtoToJSON,
    LoginResponseDtoFromJSON,
    LoginResponseDtoToJSON,
} from '../models/index';

export interface ApiAuthorizeChangePasswordPostRequest {
    changePasswordRequestDto?: ChangePasswordRequestDto;
}

export interface ApiAuthorizeForgetPasswordPostRequest {
    forgetPasswordRequestDto?: ForgetPasswordRequestDto;
}

export interface ApiAuthorizeLoginPostRequest {
    loginRequestDto?: LoginRequestDto;
}

/**
 * 
 */
export class AuthorizeApi extends runtime.BaseAPI {

    /**
     */
    async apiAuthorizeChangePasswordPostRaw(requestParameters: ApiAuthorizeChangePasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Authorize/changePassword`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangePasswordRequestDtoToJSON(requestParameters['changePasswordRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuthorizeChangePasswordPost(requestParameters: ApiAuthorizeChangePasswordPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthorizeChangePasswordPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAuthorizeCheckTokenPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckTokenResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Authorize/checkToken`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckTokenResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthorizeCheckTokenPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckTokenResponseDto> {
        const response = await this.apiAuthorizeCheckTokenPostRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthorizeDontTouchGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Authorize/dontTouch`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuthorizeDontTouchGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthorizeDontTouchGetRaw(initOverrides);
    }

    /**
     */
    async apiAuthorizeForgetPasswordPostRaw(requestParameters: ApiAuthorizeForgetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Authorize/forgetPassword`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ForgetPasswordRequestDtoToJSON(requestParameters['forgetPasswordRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuthorizeForgetPasswordPost(requestParameters: ApiAuthorizeForgetPasswordPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthorizeForgetPasswordPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAuthorizeLoginPostRaw(requestParameters: ApiAuthorizeLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Authorize/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestDtoToJSON(requestParameters['loginRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthorizeLoginPost(requestParameters: ApiAuthorizeLoginPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponseDto> {
        const response = await this.apiAuthorizeLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
