/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReviewResponseDto,
  SubmitReviewRequestDto,
  TripReviewDataResponseDto,
  TripReviewResponseDto,
  UpdateTripReviewRequestDto,
} from '../models/index';
import {
    ReviewResponseDtoFromJSON,
    ReviewResponseDtoToJSON,
    SubmitReviewRequestDtoFromJSON,
    SubmitReviewRequestDtoToJSON,
    TripReviewDataResponseDtoFromJSON,
    TripReviewDataResponseDtoToJSON,
    TripReviewResponseDtoFromJSON,
    TripReviewResponseDtoToJSON,
    UpdateTripReviewRequestDtoFromJSON,
    UpdateTripReviewRequestDtoToJSON,
} from '../models/index';

export interface ApiReviewAllReviewsGetRequest {
    limit: number;
    offset: number;
}

export interface ApiReviewPlatformReviewsGetRequest {
    limit: number;
    offset: number;
}

export interface ApiReviewSubmitReviewPostRequest {
    submitReviewRequestDto?: SubmitReviewRequestDto;
}

export interface ApiReviewTripReviewForSubmitGetRequest {
    token: string;
}

export interface ApiReviewUpdateReviewPostRequest {
    updateTripReviewRequestDto?: UpdateTripReviewRequestDto;
}

export interface ApiReviewUserReviewsGetRequest {
    userId: number;
}

/**
 * 
 */
export class ReviewApi extends runtime.BaseAPI {

    /**
     */
    async apiReviewAllReviewsGetRaw(requestParameters: ApiReviewAllReviewsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TripReviewDataResponseDto>>> {
        if (requestParameters['limit'] == null) {
            throw new runtime.RequiredError(
                'limit',
                'Required parameter "limit" was null or undefined when calling apiReviewAllReviewsGet().'
            );
        }

        if (requestParameters['offset'] == null) {
            throw new runtime.RequiredError(
                'offset',
                'Required parameter "offset" was null or undefined when calling apiReviewAllReviewsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['Limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['Offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Review/allReviews`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TripReviewDataResponseDtoFromJSON));
    }

    /**
     */
    async apiReviewAllReviewsGet(requestParameters: ApiReviewAllReviewsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TripReviewDataResponseDto>> {
        const response = await this.apiReviewAllReviewsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiReviewPlatformReviewsGetRaw(requestParameters: ApiReviewPlatformReviewsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReviewResponseDto>>> {
        if (requestParameters['limit'] == null) {
            throw new runtime.RequiredError(
                'limit',
                'Required parameter "limit" was null or undefined when calling apiReviewPlatformReviewsGet().'
            );
        }

        if (requestParameters['offset'] == null) {
            throw new runtime.RequiredError(
                'offset',
                'Required parameter "offset" was null or undefined when calling apiReviewPlatformReviewsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['Limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['Offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Review/platformReviews`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReviewResponseDtoFromJSON));
    }

    /**
     */
    async apiReviewPlatformReviewsGet(requestParameters: ApiReviewPlatformReviewsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReviewResponseDto>> {
        const response = await this.apiReviewPlatformReviewsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiReviewSubmitReviewPostRaw(requestParameters: ApiReviewSubmitReviewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Review/submitReview`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitReviewRequestDtoToJSON(requestParameters['submitReviewRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiReviewSubmitReviewPost(requestParameters: ApiReviewSubmitReviewPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiReviewSubmitReviewPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiReviewTripReviewForSubmitGetRaw(requestParameters: ApiReviewTripReviewForSubmitGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TripReviewResponseDto>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling apiReviewTripReviewForSubmitGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['token'] != null) {
            queryParameters['Token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Review/tripReviewForSubmit`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TripReviewResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiReviewTripReviewForSubmitGet(requestParameters: ApiReviewTripReviewForSubmitGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TripReviewResponseDto> {
        const response = await this.apiReviewTripReviewForSubmitGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiReviewUpdateReviewPostRaw(requestParameters: ApiReviewUpdateReviewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Review/updateReview`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTripReviewRequestDtoToJSON(requestParameters['updateTripReviewRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiReviewUpdateReviewPost(requestParameters: ApiReviewUpdateReviewPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiReviewUpdateReviewPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiReviewUserReviewsGetRaw(requestParameters: ApiReviewUserReviewsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReviewResponseDto>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiReviewUserReviewsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['UserId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Review/userReviews`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReviewResponseDtoFromJSON));
    }

    /**
     */
    async apiReviewUserReviewsGet(requestParameters: ApiReviewUserReviewsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReviewResponseDto>> {
        const response = await this.apiReviewUserReviewsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
