/* tslint:disable */
/* eslint-disable */
/**
 * My API Merin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddVehicleRequestDto,
  UpdateVehicleRequestDto,
  VehicleResponseDto,
  VehicleTransportVerificationRequestDto,
} from '../models/index';
import {
    AddVehicleRequestDtoFromJSON,
    AddVehicleRequestDtoToJSON,
    UpdateVehicleRequestDtoFromJSON,
    UpdateVehicleRequestDtoToJSON,
    VehicleResponseDtoFromJSON,
    VehicleResponseDtoToJSON,
    VehicleTransportVerificationRequestDtoFromJSON,
    VehicleTransportVerificationRequestDtoToJSON,
} from '../models/index';

export interface ApiVehiclesPhotosPostRequest {
    id: number;
    frontPhoto: Blob;
    rearPhoto: Blob;
    leftSidePhoto: Blob;
    rightSidePhoto: Blob;
    interierPhoto1: Blob;
    interierPhoto2: Blob;
    technicalCertificate1: Blob;
    insurance: Blob;
    technicalCertificate2?: Blob;
}

export interface ApiVehiclesPhotosPutRequest {
    id: number;
    frontPhoto?: Blob;
    rearPhoto?: Blob;
    leftSidePhoto?: Blob;
    rightSidePhoto?: Blob;
    interierPhoto1?: Blob;
    interierPhoto2?: Blob;
    technicalCertificate1?: Blob;
    technicalCertificate2?: Blob;
    insurance?: Blob;
}

export interface ApiVehiclesTransportVerificationPostRequest {
    vehicleTransportVerificationRequestDto?: VehicleTransportVerificationRequestDto;
}

export interface ApiVehiclesVehicleGetRequest {
    idVehicle: number;
}

export interface ApiVehiclesVehiclePostRequest {
    addVehicleRequestDto?: AddVehicleRequestDto;
}

export interface ApiVehiclesVehiclePutRequest {
    updateVehicleRequestDto?: UpdateVehicleRequestDto;
}

/**
 * 
 */
export class VehiclesApi extends runtime.BaseAPI {

    /**
     */
    async apiVehiclesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VehicleResponseDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Vehicles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VehicleResponseDtoFromJSON));
    }

    /**
     */
    async apiVehiclesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VehicleResponseDto>> {
        const response = await this.apiVehiclesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiVehiclesPhotosPostRaw(requestParameters: ApiVehiclesPhotosPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiVehiclesPhotosPost().'
            );
        }

        if (requestParameters['frontPhoto'] == null) {
            throw new runtime.RequiredError(
                'frontPhoto',
                'Required parameter "frontPhoto" was null or undefined when calling apiVehiclesPhotosPost().'
            );
        }

        if (requestParameters['rearPhoto'] == null) {
            throw new runtime.RequiredError(
                'rearPhoto',
                'Required parameter "rearPhoto" was null or undefined when calling apiVehiclesPhotosPost().'
            );
        }

        if (requestParameters['leftSidePhoto'] == null) {
            throw new runtime.RequiredError(
                'leftSidePhoto',
                'Required parameter "leftSidePhoto" was null or undefined when calling apiVehiclesPhotosPost().'
            );
        }

        if (requestParameters['rightSidePhoto'] == null) {
            throw new runtime.RequiredError(
                'rightSidePhoto',
                'Required parameter "rightSidePhoto" was null or undefined when calling apiVehiclesPhotosPost().'
            );
        }

        if (requestParameters['interierPhoto1'] == null) {
            throw new runtime.RequiredError(
                'interierPhoto1',
                'Required parameter "interierPhoto1" was null or undefined when calling apiVehiclesPhotosPost().'
            );
        }

        if (requestParameters['interierPhoto2'] == null) {
            throw new runtime.RequiredError(
                'interierPhoto2',
                'Required parameter "interierPhoto2" was null or undefined when calling apiVehiclesPhotosPost().'
            );
        }

        if (requestParameters['technicalCertificate1'] == null) {
            throw new runtime.RequiredError(
                'technicalCertificate1',
                'Required parameter "technicalCertificate1" was null or undefined when calling apiVehiclesPhotosPost().'
            );
        }

        if (requestParameters['insurance'] == null) {
            throw new runtime.RequiredError(
                'insurance',
                'Required parameter "insurance" was null or undefined when calling apiVehiclesPhotosPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('Id', requestParameters['id'] as any);
        }

        if (requestParameters['frontPhoto'] != null) {
            formParams.append('FrontPhoto', requestParameters['frontPhoto'] as any);
        }

        if (requestParameters['rearPhoto'] != null) {
            formParams.append('RearPhoto', requestParameters['rearPhoto'] as any);
        }

        if (requestParameters['leftSidePhoto'] != null) {
            formParams.append('LeftSidePhoto', requestParameters['leftSidePhoto'] as any);
        }

        if (requestParameters['rightSidePhoto'] != null) {
            formParams.append('RightSidePhoto', requestParameters['rightSidePhoto'] as any);
        }

        if (requestParameters['interierPhoto1'] != null) {
            formParams.append('InterierPhoto1', requestParameters['interierPhoto1'] as any);
        }

        if (requestParameters['interierPhoto2'] != null) {
            formParams.append('InterierPhoto2', requestParameters['interierPhoto2'] as any);
        }

        if (requestParameters['technicalCertificate1'] != null) {
            formParams.append('TechnicalCertificate1', requestParameters['technicalCertificate1'] as any);
        }

        if (requestParameters['technicalCertificate2'] != null) {
            formParams.append('TechnicalCertificate2', requestParameters['technicalCertificate2'] as any);
        }

        if (requestParameters['insurance'] != null) {
            formParams.append('Insurance', requestParameters['insurance'] as any);
        }


        let urlPath = `/api/Vehicles/photos`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiVehiclesPhotosPost(requestParameters: ApiVehiclesPhotosPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiVehiclesPhotosPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiVehiclesPhotosPutRaw(requestParameters: ApiVehiclesPhotosPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiVehiclesPhotosPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['id'] != null) {
            formParams.append('Id', requestParameters['id'] as any);
        }

        if (requestParameters['frontPhoto'] != null) {
            formParams.append('FrontPhoto', requestParameters['frontPhoto'] as any);
        }

        if (requestParameters['rearPhoto'] != null) {
            formParams.append('RearPhoto', requestParameters['rearPhoto'] as any);
        }

        if (requestParameters['leftSidePhoto'] != null) {
            formParams.append('LeftSidePhoto', requestParameters['leftSidePhoto'] as any);
        }

        if (requestParameters['rightSidePhoto'] != null) {
            formParams.append('RightSidePhoto', requestParameters['rightSidePhoto'] as any);
        }

        if (requestParameters['interierPhoto1'] != null) {
            formParams.append('InterierPhoto1', requestParameters['interierPhoto1'] as any);
        }

        if (requestParameters['interierPhoto2'] != null) {
            formParams.append('InterierPhoto2', requestParameters['interierPhoto2'] as any);
        }

        if (requestParameters['technicalCertificate1'] != null) {
            formParams.append('TechnicalCertificate1', requestParameters['technicalCertificate1'] as any);
        }

        if (requestParameters['technicalCertificate2'] != null) {
            formParams.append('TechnicalCertificate2', requestParameters['technicalCertificate2'] as any);
        }

        if (requestParameters['insurance'] != null) {
            formParams.append('Insurance', requestParameters['insurance'] as any);
        }


        let urlPath = `/api/Vehicles/photos`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiVehiclesPhotosPut(requestParameters: ApiVehiclesPhotosPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiVehiclesPhotosPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiVehiclesTransportVerificationPostRaw(requestParameters: ApiVehiclesTransportVerificationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Vehicles/transportVerification`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VehicleTransportVerificationRequestDtoToJSON(requestParameters['vehicleTransportVerificationRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiVehiclesTransportVerificationPost(requestParameters: ApiVehiclesTransportVerificationPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiVehiclesTransportVerificationPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiVehiclesVehicleGetRaw(requestParameters: ApiVehiclesVehicleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VehicleResponseDto>> {
        if (requestParameters['idVehicle'] == null) {
            throw new runtime.RequiredError(
                'idVehicle',
                'Required parameter "idVehicle" was null or undefined when calling apiVehiclesVehicleGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['idVehicle'] != null) {
            queryParameters['IdVehicle'] = requestParameters['idVehicle'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Vehicles/vehicle`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiVehiclesVehicleGet(requestParameters: ApiVehiclesVehicleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VehicleResponseDto> {
        const response = await this.apiVehiclesVehicleGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiVehiclesVehiclePostRaw(requestParameters: ApiVehiclesVehiclePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Vehicles/vehicle`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddVehicleRequestDtoToJSON(requestParameters['addVehicleRequestDto']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiVehiclesVehiclePost(requestParameters: ApiVehiclesVehiclePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.apiVehiclesVehiclePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiVehiclesVehiclePutRaw(requestParameters: ApiVehiclesVehiclePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Vehicles/vehicle`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateVehicleRequestDtoToJSON(requestParameters['updateVehicleRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiVehiclesVehiclePut(requestParameters: ApiVehiclesVehiclePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiVehiclesVehiclePutRaw(requestParameters, initOverrides);
    }

}
