import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Header} from "@/src/components/compositions/header/header";
import {AuthProvider} from "@/src/app/contexts/AuthContext";
import {AuthorizationService} from "@/src/services/AuthorizationService";
import {AppProvider} from "@/src/app/contexts/AppContext";
import {AppLoader} from "@/src/components/components/app-loader/app-loader";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from "@/src/i18n/routing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
    children: React.ReactNode;
    params: Promise<{locale: string}>;
}

export default async function RootLayout(props: IRootLayoutProps) {
    const {params, children} = props;
    const user = await AuthorizationService.getUserJson();
    const {locale} = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }

    return <html lang="cs">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <NextIntlClientProvider>
                <AuthProvider initialUser={user}>
                    <AppProvider>
                        <AppLoader />
                        <Header user={user} />
                        {children}
                    </AppProvider>
                </AuthProvider>
            </NextIntlClientProvider>
        </body>
    </html>
}